{"train_number":"12723","train_name":"TELANGANA  EXP"},
{"train_number":"22416","train_name":"A P EXP"},
{"train_number":"12724","train_name":"TELANGANA EXP"},
{"train_number":"12707","train_name":"A P SMPRK KRNTI"},
{"train_number":"15909","train_name":"ABADH ASSAM EXP"},
{"train_number":"15609","train_name":""},
{"train_number":"18242","train_name":""},
{"train_number":"11266","train_name":"ABKP JBP EXPRES"},
{"train_number":"58702","train_name":"ABKP SDL PASSENGER"},
{"train_number":"54703","train_name":"ABS JU PASSENGER"},
{"train_number":"07509","train_name":""},
{"train_number":"09416","train_name":""},
{"train_number":"09427","train_name":""},
{"train_number":"09018","train_name":""},
{"train_number":"14804","train_name":"ADI BGKT EXPRES"},
{"train_number":"04804","train_name":""},
{"train_number":"09421","train_name":""},
{"train_number":"19130","train_name":""},
{"train_number":"02713","train_name":""},
{"train_number":"19420","train_name":"ADI CHENNAI EXP"},
{"train_number":"09417","train_name":""},
{"train_number":"12931","train_name":"ADI DOUBLE DECK"},
{"train_number":"12267","train_name":"ADI DURONTO EXP"},
{"train_number":"12298","train_name":"ADI DURONTO EXP"},
{"train_number":"09425","train_name":""},
{"train_number":"19223","train_name":"ADI JAT EXPRESS"},
{"train_number":"02207","train_name":""},
{"train_number":"19606","train_name":""},
{"train_number":"09407","train_name":""},
{"train_number":"09413","train_name":""},
{"train_number":"09420","train_name":""},
{"train_number":"09411","train_name":""},
{"train_number":"09409","train_name":""},
{"train_number":"12844","train_name":"ADI PURI EXP"},
{"train_number":"18406","train_name":"ADI PURI EXP"},
{"train_number":"07017","train_name":""},
{"train_number":"12958","train_name":"ADI SJ RAJDHANI"},
{"train_number":"19415","train_name":"ADI SVDK EXPRES"},
{"train_number":"19944","train_name":"ADI UDZ EXPRESS"},
{"train_number":"19407","train_name":"ADI VARANASI EX"},
{"train_number":"16501","train_name":"ADI YPR EXPRESS"},
{"train_number":"12547","train_name":"AF ADI SF EXP"},
{"train_number":"12195","train_name":"AF AII INTERCIT"},
{"train_number":"09612","train_name":""},
{"train_number":"12036","train_name":"AF JP SHATABDI"},
{"train_number":"15055","train_name":"AF RMR EXPRESS"},
{"train_number":"12954","train_name":"AG KRANTI RJDHN"},
{"train_number":"12320","train_name":"AGC KOAA EXP"},
{"train_number":"13168","train_name":"AGC KOAA EXP"},
{"train_number":"01436","train_name":""},
{"train_number":"12342","train_name":"AGNIBINA EXPRES"},
{"train_number":"12341","train_name":"AGNIBINA EXPRES"},
{"train_number":"12548","train_name":"AGRA SUPER FAST"},
{"train_number":"52575","train_name":"JOYRIDE DIESEL"},
{"train_number":"15696","train_name":""},
{"train_number":"22646","train_name":"AHILYANAGARI EX"},
{"train_number":"22645","train_name":"AHILYANAGARI EX"},
{"train_number":"16326","train_name":""},
{"train_number":"11096","train_name":"AHIMSA EXPRESS"},
{"train_number":"11095","train_name":"AHIMSA EXPRESS"},
{"train_number":"16502","train_name":"AHMADABAD EXP"},
{"train_number":"59440","train_name":"ADI BCT PASSENGER"},
{"train_number":"59439","train_name":"BCT ADI PASSENGER"},
{"train_number":"19405","train_name":""},
{"train_number":"09419","train_name":""},
{"train_number":"11050","train_name":"AHMEDABAD EXP"},
{"train_number":"59441","train_name":"BCT ADI PASSENGER"},
{"train_number":"59442","train_name":"ADI BCT PASSENGER"},
{"train_number":"09649","train_name":""},
{"train_number":"12196","train_name":"AII AF INTERCIT"},
{"train_number":"05712","train_name":""},
{"train_number":"22996","train_name":"AII BDTS SF EXP"},
{"train_number":"09611","train_name":""},
{"train_number":"09619","train_name":""},
{"train_number":"09602","train_name":"HOLIDAY SPL"},
{"train_number":"09601","train_name":""},
{"train_number":"13424","train_name":"AII BGP EXP"},
{"train_number":"05286","train_name":""},
{"train_number":"12983","train_name":"AII CDG G RATH"},
{"train_number":"05104","train_name":""},
{"train_number":"05238","train_name":""},
{"train_number":"12990","train_name":"AII DDR  EXPRES"},
{"train_number":"09627","train_name":"HOLIDAY SPL"},
{"train_number":"04042","train_name":""},
{"train_number":"18208","train_name":"AII DURG EXP"},
{"train_number":"19609","train_name":"AII HW EXP"},
{"train_number":"09640","train_name":""},
{"train_number":"03002","train_name":""},
{"train_number":"17019","train_name":"AII HYB EXP"},
{"train_number":"12719","train_name":"AII HYB SF EXP"},
{"train_number":"07019","train_name":""},
{"train_number":"07126","train_name":""},
{"train_number":"09312","train_name":""},
{"train_number":"12066","train_name":"AII JAN SHATABD"},
{"train_number":"12413","train_name":"AII JAT EXPRESS"},
{"train_number":"09720","train_name":""},
{"train_number":"09621","train_name":""},
{"train_number":"09625","train_name":"UDZ AWR SF SPL"},
{"train_number":"54802","train_name":"AII JU PASSENGER"},
{"train_number":"12723","train_name":"TELANGANA  EXP"},
{"train_number":"22416","train_name":"A P EXP"},
{"train_number":"12723","train_name":"TELANGANA  EXP"},
{"train_number":"22416","train_name":"A P EXP"},
{"train_number":"12724","train_name":"TELANGANA EXP"},
{"train_number":"12707","train_name":"A P SMPRK KRNTI"},
{"train_number":"15909","train_name":"ABADH ASSAM EXP"},
{"train_number":"15609","train_name":""},
{"train_number":"18242","train_name":""},
{"train_number":"11266","train_name":"ABKP JBP EXPRES"},
{"train_number":"58702","train_name":"ABKP SDL PASSENGER"},
{"train_number":"54703","train_name":"ABS JU PASSENGER"},
{"train_number":"07509","train_name":""},
{"train_number":"09416","train_name":""},
{"train_number":"09427","train_name":""},
{"train_number":"09018","train_name":""},
{"train_number":"14804","train_name":"ADI BGKT EXPRES"},
{"train_number":"04804","train_name":""},
{"train_number":"09421","train_name":""},
{"train_number":"19130","train_name":""},
{"train_number":"02713","train_name":""},
{"train_number":"19420","train_name":"ADI CHENNAI EXP"},
{"train_number":"09417","train_name":""},
{"train_number":"12931","train_name":"ADI DOUBLE DECK"},
{"train_number":"12267","train_name":"ADI DURONTO EXP"},
{"train_number":"12298","train_name":"ADI DURONTO EXP"},
{"train_number":"09425","train_name":""},
{"train_number":"19223","train_name":"ADI JAT EXPRESS"},
{"train_number":"02207","train_name":""},
{"train_number":"19606","train_name":""},
{"train_number":"09407","train_name":""},
{"train_number":"09413","train_name":""},
{"train_number":"09420","train_name":""},
{"train_number":"09411","train_name":""},
{"train_number":"09409","train_name":""},
{"train_number":"12844","train_name":"ADI PURI EXP"},
{"train_number":"18406","train_name":"ADI PURI EXP"},
{"train_number":"07017","train_name":""},
{"train_number":"12958","train_name":"ADI SJ RAJDHANI"},
{"train_number":"19415","train_name":"ADI SVDK EXPRES"},
{"train_number":"19944","train_name":"ADI UDZ EXPRESS"},
{"train_number":"19407","train_name":"ADI VARANASI EX"},
{"train_number":"16501","train_name":"ADI YPR EXPRESS"},
{"train_number":"12547","train_name":"AF ADI SF EXP"},
{"train_number":"12195","train_name":"AF AII INTERCIT"},
{"train_number":"09612","train_name":""},
{"train_number":"12036","train_name":"AF JP SHATABDI"},
{"train_number":"15055","train_name":"AF RMR EXPRESS"},
{"train_number":"12954","train_name":"AG KRANTI RJDHN"},
{"train_number":"12320","train_name":"AGC KOAA EXP"},
{"train_number":"13168","train_name":"AGC KOAA EXP"},
{"train_number":"01436","train_name":""},
{"train_number":"12342","train_name":"AGNIBINA EXPRES"},
{"train_number":"12341","train_name":"AGNIBINA EXPRES"},
{"train_number":"12548","train_name":"AGRA SUPER FAST"},
{"train_number":"52575","train_name":"JOYRIDE DIESEL"},
{"train_number":"15696","train_name":""},
{"train_number":"22646","train_name":"AHILYANAGARI EX"},
{"train_number":"22645","train_name":"AHILYANAGARI EX"},
{"train_number":"16326","train_name":""},
{"train_number":"11096","train_name":"AHIMSA EXPRESS"},
{"train_number":"11095","train_name":"AHIMSA EXPRESS"},
{"train_number":"16502","train_name":"AHMADABAD EXP"},
{"train_number":"59440","train_name":"ADI BCT PASSENGER"},
{"train_number":"59439","train_name":"BCT ADI PASSENGER"},
{"train_number":"19405","train_name":""},
{"train_number":"09419","train_name":""},
{"train_number":"11050","train_name":"AHMEDABAD EXP"},
{"train_number":"59441","train_name":"BCT ADI PASSENGER"},
{"train_number":"59442","train_name":"ADI BCT PASSENGER"},
{"train_number":"09649","train_name":""},
{"train_number":"12196","train_name":"AII AF INTERCIT"},
{"train_number":"05712","train_name":""},
{"train_number":"22996","train_name":"AII BDTS SF EXP"},
{"train_number":"09611","train_name":""},
{"train_number":"09619","train_name":""},
{"train_number":"09602","train_name":"HOLIDAY SPL"},
{"train_number":"09601","train_name":""},
{"train_number":"13424","train_name":"AII BGP EXP"},
{"train_number":"05286","train_name":""},
{"train_number":"12983","train_name":"AII CDG G RATH"},
{"train_number":"05104","train_name":""},
{"train_number":"05238","train_name":""},
{"train_number":"12990","train_name":"AII DDR  EXPRES"},
{"train_number":"09627","train_name":"HOLIDAY SPL"},
{"train_number":"04042","train_name":""},
{"train_number":"18208","train_name":"AII DURG EXP"},
{"train_number":"19609","train_name":"AII HW EXP"},
{"train_number":"09640","train_name":""},
{"train_number":"03002","train_name":""},
{"train_number":"17019","train_name":"AII HYB EXP"},
{"train_number":"12719","train_name":"AII HYB SF EXP"},
{"train_number":"07019","train_name":""},
{"train_number":"07126","train_name":""},
{"train_number":"09312","train_name":""},
{"train_number":"12066","train_name":"AII JAN SHATABD"},
