[
{"train_number":"12723","train_name":"TELANGANA  EXP"},
{"train_number":"22416","train_name":"A P EXP"},
{"train_number":"12724","train_name":"TELANGANA EXP"},
{"train_number":"12707","train_name":"A P SMPRK KRNTI"},
{"train_number":"15909","train_name":"ABADH ASSAM EXP"},
{"train_number":"15609","train_name":""},
{"train_number":"18242","train_name":""},
{"train_number":"11266","train_name":"ABKP JBP EXPRES"},
{"train_number":"58702","train_name":"ABKP SDL PASSENGER"},
{"train_number":"54703","train_name":"ABS JU PASSENGER"},
{"train_number":"07509","train_name":""},
{"train_number":"09416","train_name":""},
{"train_number":"09427","train_name":""},
{"train_number":"09018","train_name":""},
{"train_number":"14804","train_name":"ADI BGKT EXPRES"},
{"train_number":"04804","train_name":""},
{"train_number":"09421","train_name":""},
{"train_number":"19130","train_name":""},
{"train_number":"02713","train_name":""},
{"train_number":"19420","train_name":"ADI CHENNAI EXP"},
{"train_number":"09417","train_name":""},
{"train_number":"12931","train_name":"ADI DOUBLE DECK"},
{"train_number":"12267","train_name":"ADI DURONTO EXP"},
{"train_number":"12298","train_name":"ADI DURONTO EXP"},
{"train_number":"09425","train_name":""},
{"train_number":"19223","train_name":"ADI JAT EXPRESS"},
{"train_number":"02207","train_name":""},
{"train_number":"19606","train_name":""},
{"train_number":"09407","train_name":""},
{"train_number":"09413","train_name":""},
{"train_number":"09420","train_name":""},
{"train_number":"09411","train_name":""},
{"train_number":"09409","train_name":""},
{"train_number":"12844","train_name":"ADI PURI EXP"},
{"train_number":"18406","train_name":"ADI PURI EXP"},
{"train_number":"07017","train_name":""},
{"train_number":"12958","train_name":"ADI SJ RAJDHANI"},
{"train_number":"19415","train_name":"ADI SVDK EXPRES"},
{"train_number":"19944","train_name":"ADI UDZ EXPRESS"},
{"train_number":"19407","train_name":"ADI VARANASI EX"},
{"train_number":"16501","train_name":"ADI YPR EXPRESS"},
{"train_number":"12547","train_name":"AF ADI SF EXP"},
{"train_number":"12195","train_name":"AF AII INTERCIT"},
{"train_number":"09612","train_name":""},
{"train_number":"12036","train_name":"AF JP SHATABDI"},
{"train_number":"15055","train_name":"AF RMR EXPRESS"},
{"train_number":"12954","train_name":"AG KRANTI RJDHN"},
{"train_number":"12320","train_name":"AGC KOAA EXP"},
{"train_number":"13168","train_name":"AGC KOAA EXP"},
{"train_number":"01436","train_name":""},
{"train_number":"12342","train_name":"AGNIBINA EXPRES"},
{"train_number":"12341","train_name":"AGNIBINA EXPRES"},
{"train_number":"12548","train_name":"AGRA SUPER FAST"},
{"train_number":"52575","train_name":"JOYRIDE DIESEL"},
{"train_number":"15696","train_name":""},
{"train_number":"22646","train_name":"AHILYANAGARI EX"},
{"train_number":"22645","train_name":"AHILYANAGARI EX"},
{"train_number":"16326","train_name":""},
{"train_number":"11096","train_name":"AHIMSA EXPRESS"},
{"train_number":"11095","train_name":"AHIMSA EXPRESS"},
{"train_number":"16502","train_name":"AHMADABAD EXP"},
{"train_number":"59440","train_name":"ADI BCT PASSENGER"},
{"train_number":"59439","train_name":"BCT ADI PASSENGER"},
{"train_number":"19405","train_name":""},
{"train_number":"09419","train_name":""},
{"train_number":"11050","train_name":"AHMEDABAD EXP"},
{"train_number":"59441","train_name":"BCT ADI PASSENGER"},
{"train_number":"59442","train_name":"ADI BCT PASSENGER"},
{"train_number":"09649","train_name":""},
{"train_number":"12196","train_name":"AII AF INTERCIT"},
{"train_number":"05712","train_name":""},
{"train_number":"22996","train_name":"AII BDTS SF EXP"},
{"train_number":"09611","train_name":""},
{"train_number":"09619","train_name":""},
{"train_number":"09602","train_name":"HOLIDAY SPL"},
{"train_number":"09601","train_name":""},
{"train_number":"13424","train_name":"AII BGP EXP"},
{"train_number":"05286","train_name":""},
{"train_number":"12983","train_name":"AII CDG G RATH"},
{"train_number":"05104","train_name":""},
{"train_number":"05238","train_name":""},
{"train_number":"12990","train_name":"AII DDR  EXPRES"},
{"train_number":"09627","train_name":"HOLIDAY SPL"},
{"train_number":"04042","train_name":""},
{"train_number":"18208","train_name":"AII DURG EXP"},
{"train_number":"19609","train_name":"AII HW EXP"},
{"train_number":"09640","train_name":""},
{"train_number":"03002","train_name":""},
{"train_number":"17019","train_name":"AII HYB EXP"},
{"train_number":"12719","train_name":"AII HYB SF EXP"},
{"train_number":"07019","train_name":""},
{"train_number":"07126","train_name":""},
{"train_number":"09312","train_name":""},
{"train_number":"12066","train_name":"AII JAN SHATABD"},
{"train_number":"12413","train_name":"AII JAT EXPRESS"},
{"train_number":"09720","train_name":""},
{"train_number":"09621","train_name":""},
{"train_number":"09625","train_name":"UDZ AWR SF SPL"},
{"train_number":"54802","train_name":"AII JU PASSENGER"},
{"train_number":"09615","train_name":""},
{"train_number":"07130","train_name":""},
{"train_number":"03138","train_name":""},
{"train_number":"19608","train_name":"AII KOAA EXP"},
{"train_number":"16209","train_name":"AII MYS EXPRESS"},
{"train_number":"22211","train_name":""},
{"train_number":"08422","train_name":""},
{"train_number":"18422","train_name":"AII PURI EXP"},
{"train_number":"19654","train_name":"AII RTM EXP"},
{"train_number":"12988","train_name":"AII SDAH EXPRES"},
{"train_number":"03180","train_name":""},
{"train_number":"19603","train_name":""},
{"train_number":"09609","train_name":""},
{"train_number":"19607","train_name":"AII WKLY EXP"},
{"train_number":"17063","train_name":"AJANTA EXPRESS"},
{"train_number":"17064","train_name":"AJANTA EXPRESS"},
{"train_number":"19611","train_name":"AJMER ASR EXP"},
{"train_number":"19613","train_name":"AJMER ASR EXP"},
{"train_number":"12989","train_name":"AJMER EXPRESS"},
{"train_number":"16210","train_name":"AJMER EXPRESS"},
{"train_number":"19411","train_name":"AJMER INTERCITY"},
{"train_number":"12016","train_name":"AJMER SHTBDI"},
{"train_number":"12015","train_name":"AJMER SHTBDI"},
{"train_number":"09650","train_name":""},
{"train_number":"12120","train_name":""},
{"train_number":"11202","train_name":"AJNI LTT EXPRES"},
{"train_number":"17640","train_name":"AK KCG EXP"},
{"train_number":"52994","train_name":"AK MHOW PASSENGER"},
{"train_number":"07507","train_name":""},
{"train_number":"12318","train_name":"AKAL TAKHAT EXP"},
{"train_number":"12317","train_name":"AKAL TAKHT EXP"},
{"train_number":"14312","train_name":"ALA HAZRAT EXP"},
{"train_number":"14311","train_name":"ALA HAZRAT EXP"},
{"train_number":"07092","train_name":""},
{"train_number":"09430","train_name":""},
{"train_number":"09428","train_name":""},
{"train_number":"04421","train_name":"KGM NDLS SPL"},
{"train_number":"04117","train_name":""},
{"train_number":"07240","train_name":""},
{"train_number":"04001","train_name":""},
{"train_number":"12276","train_name":"ALD DURONTO EXP"},
{"train_number":"12293","train_name":"ALD DURONTO EXP"},
{"train_number":"14115","train_name":"ALD HW EXP"},
{"train_number":"04120","train_name":""},
{"train_number":"09314","train_name":""},
{"train_number":"22442","train_name":""},
{"train_number":"04121","train_name":""},
{"train_number":"04131","train_name":""},
{"train_number":"12403","train_name":"ALD JP EXPRESS"},
{"train_number":"12294","train_name":"ALD LTT DURONTO"},
{"train_number":"04127","train_name":""},
{"train_number":"12564","train_name":""},
{"train_number":"04115","train_name":""},
{"train_number":"01006","train_name":""},
{"train_number":"04111","train_name":""},
{"train_number":"04423","train_name":""},
{"train_number":"07512","train_name":""},
{"train_number":"07514","train_name":""},
{"train_number":"04124","train_name":""},
{"train_number":"09016","train_name":""},
{"train_number":"04113","train_name":""},
{"train_number":"08576","train_name":""},
{"train_number":"09429","train_name":""},
{"train_number":"09313","train_name":""},
{"train_number":"16308","train_name":"ALLEPPEY EXP"},
{"train_number":"22639","train_name":"ALLEPPEY EXP"},
{"train_number":"12587","train_name":"AMAR NATH EXP"},
{"train_number":"18047","train_name":"AMARAVATHI EXP"},
{"train_number":"17225","train_name":"AMARAVATHI EXP"},
{"train_number":"17226","train_name":"AMARAVATI EXP"},
{"train_number":"12854","train_name":"AMARKANTAK EXP"},
{"train_number":"12853","train_name":"AMARKANTAK EXP"},
{"train_number":"15097","train_name":"AMARNATH EXP"},
{"train_number":"15098","train_name":"AMARNATH EXP"},
{"train_number":"15653","train_name":"AMARNATH EXPRES"},
{"train_number":"11265","train_name":"AMBIKAPUR EXPRE"},
{"train_number":"13138","train_name":"AMH KOAA EXP"},
{"train_number":"11054","train_name":"AMH LTT EXP"},
{"train_number":"12119","train_name":""},
{"train_number":"12159","train_name":"AMI JBP SUP EXP"},
{"train_number":"11406","train_name":"AMI PUNE EXP"},
{"train_number":"12766","train_name":"AMI TPTY SUP EX"},
{"train_number":"09050","train_name":""},
{"train_number":"12112","train_name":"AMRAVATI CSTM E"},
{"train_number":"16343","train_name":"AMRITHA EXPRESS"},
{"train_number":"16344","train_name":"AMRITHA EXPRESS"},
{"train_number":"13049","train_name":"AMRITSAR EXP"},
{"train_number":"12483","train_name":"AMRITSAR EXP"},
{"train_number":"11057","train_name":"AMRITSAR EXPRES"},
{"train_number":"13005","train_name":"AMRITSAR MAIL"},
{"train_number":"12031","train_name":"AMRITSAR SHTBDI"},
{"train_number":"12032","train_name":"AMRITSAR SHTBDI"},
{"train_number":"12013","train_name":"AMRITSAR SHTBDI"},
{"train_number":"12014","train_name":"AMRITSAR SHTBDI"},
{"train_number":"22128","train_name":"ANANDWAN EXP"},
{"train_number":"22127","train_name":"ANANDWAN EXPRES"},
{"train_number":"16724","train_name":"ANANTAPURI EXP"},
{"train_number":"16723","train_name":"ANANTAPURI EXP"},
{"train_number":"12316","train_name":"ANANYA EXPRESS"},
{"train_number":"16032","train_name":"ANDAMAN EXPRESS"},
{"train_number":"16031","train_name":"ANDAMAN EXPRESS"},
{"train_number":"12254","train_name":"ANGA EXPRESS"},
{"train_number":"12253","train_name":"ANGA EXPRESS"},
{"train_number":"12315","train_name":"ANNANYA  EXPRES"},
{"train_number":"04422","train_name":"NDLS KGM SPL"},
{"train_number":"04118","train_name":"HOLIDAY SPL"},
{"train_number":"04028","train_name":""},
{"train_number":"03518","train_name":""},
{"train_number":"22406","train_name":"ANVT BGP G RATH"},
{"train_number":"14152","train_name":"ANVT CNB EXP"},
{"train_number":"05214","train_name":""},
{"train_number":"04053","train_name":""},
{"train_number":"12211","train_name":"ANVT GARIB RATH"},
{"train_number":"22409","train_name":"ANVT GARIB RATH"},
{"train_number":"02398","train_name":""},
{"train_number":"05038","train_name":""},
{"train_number":"05028","train_name":""},
{"train_number":"15058","train_name":"ANVT GKP EXP"},
{"train_number":"05036","train_name":""},
{"train_number":"05058","train_name":""},
{"train_number":"05052","train_name":""},
{"train_number":"05050","train_name":""},
{"train_number":"05040","train_name":""},
{"train_number":"12444","train_name":"ANVT HLZ S F EX"},
{"train_number":"12040","train_name":"NDLS KGM SHT"},
{"train_number":"13132","train_name":"ANVT KOAA EXP"},
{"train_number":"03126","train_name":""},
{"train_number":"15622","train_name":"ANVT KYQ EXPRES"},
{"train_number":"15026","train_name":"ANVT MAU EXP"},
{"train_number":"13430","train_name":"ANVT MLDT EXP"},
{"train_number":"03444","train_name":""},
{"train_number":"03210","train_name":""},
{"train_number":"02394","train_name":""},
{"train_number":"02365","train_name":""},
{"train_number":"02527","train_name":""},
{"train_number":"22488","train_name":""},
{"train_number":"12428","train_name":"ANVT REWA EXP"},
{"train_number":"03416","train_name":""},
{"train_number":"03190","train_name":""},
{"train_number":"22858","train_name":"ANVT SRC SF EXP"},
{"train_number":"08034","train_name":""},
{"train_number":"04403","train_name":""},
{"train_number":"04051","train_name":""},
{"train_number":"12708","train_name":"AP SMPRK KRANTI"},
{"train_number":"05711","train_name":""},
{"train_number":"05817","train_name":"HOLIDAY SPL"},
{"train_number":"05422","train_name":""},
{"train_number":"12885","train_name":"ARANYAK EXPRESS"},
{"train_number":"12886","train_name":"ARANYAK EXPRESS"},
{"train_number":"19707","train_name":"ARAVALI EXPRESS"},
{"train_number":"19708","train_name":"ARAVALI EXPRESS"},
{"train_number":"12356","train_name":"ARCHANA EXPRESS"},
{"train_number":"12355","train_name":"ARCHNA EXPRESS"},
{"train_number":"15814","train_name":""},
{"train_number":"15813","train_name":""},
{"train_number":"03560","train_name":""},
{"train_number":"12916","train_name":"ASHRAM EXPRESS"},
{"train_number":"12915","train_name":"ASHRAM EXPRESS"},
{"train_number":"03513","train_name":""},
{"train_number":"03517","train_name":""},
{"train_number":"12361","train_name":"ASN CSTM EXPRES"},
{"train_number":"13509","train_name":"ASN GD EXPRESS"},
{"train_number":"13507","train_name":"ASN GKP EXPRESS"},
{"train_number":"03563","train_name":""},
{"train_number":"12376","train_name":"ASN MAS EXPRESS"},
{"train_number":"03555","train_name":""},
{"train_number":"03511","train_name":""},
{"train_number":"03503","train_name":""},
{"train_number":"03557","train_name":""},
{"train_number":"03516","train_name":""},
{"train_number":"19614","train_name":"ASR AII EXP"},
{"train_number":"19612","train_name":"ASR AJMER EXP"},
{"train_number":"12242","train_name":"ASR CDG SUP"},
{"train_number":"14154","train_name":"ASR CNB EXPRESS"},
{"train_number":"15934","train_name":"ASR DBRG EXPRES"},
{"train_number":"14632","train_name":"ASR DDN EXPRESS"},
{"train_number":"54602","train_name":"ASR SDLP PASSENGER"},
{"train_number":"12054","train_name":"ASR HW JNSHTBDI"},
{"train_number":"13050","train_name":"ASR HWH EXPRESS"},
{"train_number":"13006","train_name":"ASR HWH MAIL"},
{"train_number":"19326","train_name":"ASR INDB EXPRES"},
{"train_number":"19772","train_name":""},
{"train_number":"19782","train_name":""},
{"train_number":"12484","train_name":"ASR KCVL EXPRES"},
{"train_number":"15708","train_name":"ASR KIR EXPRESS"},
{"train_number":"12358","train_name":"ASR KOAA SUP EX"},
{"train_number":"14616","train_name":"ASR LKU EXP"},
{"train_number":"11058","train_name":"ASR CSTM  EXP"},
{"train_number":"12460","train_name":"ASR NDLS EXP"},
{"train_number":"12716","train_name":"ASR NED EXPRESS"},
{"train_number":"12422","train_name":"ASR NED SF EXP"},
{"train_number":"14002","train_name":"ATTARI DLI EXP"},
{"train_number":"12953","train_name":"AUG KR RAJ EXP"},
{"train_number":"57549","train_name":"HYB AWB PASSENGER"},
{"train_number":"15910","train_name":"AVADH ASSAM EXP"},
{"train_number":"15610","train_name":""},
{"train_number":"19040","train_name":"AVADH EXPRESS"},
{"train_number":"19039","train_name":"AVADH EXPRESS"},
{"train_number":"19038","train_name":"AVADH EXPRESS"},
{"train_number":"19037","train_name":"AVADH EXPRESS"},
{"train_number":"12962","train_name":"AVANTIKA EXP"},
{"train_number":"12961","train_name":"AVANTIKA EXP"},
{"train_number":"17619","train_name":"AWB NED EXP"},
{"train_number":"07505","train_name":""},
{"train_number":"17621","train_name":"AWB RU EXPRESS"},
{"train_number":"07503","train_name":""},
{"train_number":"07405","train_name":""},
{"train_number":"14808","train_name":""},
{"train_number":"04805","train_name":"HOLIDAY SPL"},
{"train_number":"12129","train_name":"AZAD HIND EXP"},
{"train_number":"12130","train_name":"AZAD HIND EXP"},
{"train_number":"12948","train_name":"AZIMABAD EXPRES"},
{"train_number":"12947","train_name":"AZIMABAD EXPRES"},
{"train_number":"15665","train_name":"B  G  EXPRESS"},
{"train_number":"15666","train_name":"B G EXPRESS"},
{"train_number":"18450","train_name":"B NATH DHAM EXP"},
{"train_number":"18449","train_name":"B NATH DHAM EXP"},
{"train_number":"13019","train_name":"BAGH EXPRESS"},
{"train_number":"13020","train_name":"BAGH EXPRESS"},
{"train_number":"12577","train_name":"BAGMATI EXPRESS"},
{"train_number":"12578","train_name":"BAGMATI EXPRESS"},
{"train_number":"74639","train_name":""},
{"train_number":"19452","train_name":"BANDRA T EXP"},
{"train_number":"06347","train_name":""},
{"train_number":"16524","train_name":"BANGALORE EXP"},
{"train_number":"16316","train_name":"BANGALORE EXP"},
{"train_number":"16322","train_name":""},
{"train_number":"06314","train_name":""},
{"train_number":"06029","train_name":""},
{"train_number":"06572","train_name":""},
{"train_number":"12609","train_name":"BANGALORE EXP"},
{"train_number":"17236","train_name":"BANGALORE EXP"},
{"train_number":"16525","train_name":"BANGALORE EXP"},
{"train_number":"16538","train_name":""},
{"train_number":"12678","train_name":"BANGALORE EXP"},
{"train_number":"16228","train_name":"BANGALORE EXP"},
{"train_number":"16518","train_name":"BANGALORE EXP"},
{"train_number":"06590","train_name":""},
{"train_number":"12785","train_name":"BANGALORE EXP"},
{"train_number":"06516","train_name":""},
{"train_number":"12657","train_name":"BANGALORE MAIL"},
{"train_number":"56263","train_name":"MYS SBC PASSENGER"},
{"train_number":"12683","train_name":"BANGALORE SF EX"},
{"train_number":"22607","train_name":"BANGALORE SF EX"},
{"train_number":"06514","train_name":""},
{"train_number":"22694","train_name":"BANGLORE RAJDHN"},
{"train_number":"12494","train_name":""},
{"train_number":"22692","train_name":"BANGLORE RJDHNI"},
{"train_number":"13241","train_name":"BANKA RJPB EXP"},
{"train_number":"15693","train_name":""},
{"train_number":"15694","train_name":""},
{"train_number":"14555","train_name":"BAREILLY DLI EX"},
{"train_number":"14556","train_name":"BAREILLY EXP"},
{"train_number":"14313","train_name":"BAREILLY EXP"},
{"train_number":"14322","train_name":"BAREILLY EXPRES"},
{"train_number":"28624","train_name":"BARKA RJPB EXP"},
{"train_number":"14888","train_name":"BARMER  KLK EXP"},
{"train_number":"14805","train_name":"BARMER AC EXP"},
{"train_number":"17308","train_name":"BASAVA EXPRESS"},
{"train_number":"17307","train_name":"BASAVA EXPRESS"},
{"train_number":"51029","train_name":"CSTM BJP PASSENGER"},
{"train_number":"18404","train_name":"BBN CKP INT EXP"},
{"train_number":"12022","train_name":"BBN JANSHATABDI"},
{"train_number":"12021","train_name":"BBN JANSHATABDI"},
{"train_number":"18415","train_name":"BBN PURI EXP"},
{"train_number":"12831","train_name":"BBS  GARIB RATH"},
{"train_number":"12892","train_name":"BBS BPO EXPRESS"},
{"train_number":"18437","train_name":"BBS BWIP LINK E"},
{"train_number":"12830","train_name":"BBS CHENNAI EXP"},
{"train_number":"01020","train_name":""},
{"train_number":"12282","train_name":"BBS DURONTO EXP"},
{"train_number":"12281","train_name":"BBS DURONTO EXP"},
{"train_number":"12894","train_name":"BBS EXPRESS"},
{"train_number":"12073","train_name":"BBS JAN SHATABD"},
{"train_number":"12074","train_name":"BBS JAN SHATABD"},
{"train_number":"12880","train_name":"BBS LTT SF EXP"},
{"train_number":"02815","train_name":""},
{"train_number":"02281","train_name":""},
{"train_number":"22805","train_name":"BBS ANVT SUP EX"},
{"train_number":"12898","train_name":"BBS PDY EXPRESS"},
{"train_number":"08449","train_name":""},
{"train_number":"22882","train_name":"BBS PUNE EXP"},
{"train_number":"12582","train_name":"NDLS MUV SF EXP"},
{"train_number":"02882","train_name":""},
{"train_number":"22811","train_name":"BBS RAJDHANI EX"},
{"train_number":"22823","train_name":"BBS RAJDHANI EX"},
{"train_number":"18496","train_name":"BBS RMM EXPRESS"},
{"train_number":"18106","train_name":"BBS ROU INT EXP"},
{"train_number":"08464","train_name":""},
{"train_number":"22871","train_name":"BBS TPTY EXPRES"},
{"train_number":"22879","train_name":"BBS TPTY SUP EX"},
{"train_number":"02845","train_name":""},
{"train_number":"12845","train_name":"BBS BNC SUP EXP"},
{"train_number":"09017","train_name":""},
{"train_number":"09007","train_name":""},
{"train_number":"12932","train_name":"BCT DOUBLEDECKE"},
{"train_number":"22210","train_name":"BCT DURONTO"},
{"train_number":"12268","train_name":"BCT DURONTO EXP"},
{"train_number":"12955","train_name":"BCT JP EXPRESS"},
{"train_number":"04093","train_name":""},
{"train_number":"09003","train_name":""},
{"train_number":"14209","train_name":"PRG LKO INTRCTY"},
{"train_number":"02904","train_name":""},
{"train_number":"","train_name":""},
{"train_number":"09027","train_name":""},
{"train_number":"09642","train_name":""},
{"train_number":"12995","train_name":"BDTS AII UDZ EX"},
{"train_number":"09620","train_name":""},
{"train_number":"19065","train_name":"BDTS BGKT EXP"},
{"train_number":"19115","train_name":"BDTS BHUJ EXP"},
{"train_number":"09023","train_name":""},
{"train_number":"22474","train_name":"BDTS BKN SUP EX"},
{"train_number":"19203","train_name":"BDTS BVC EXP"},
{"train_number":"09231","train_name":""},
{"train_number":"19029","train_name":"BDTS DEE EXPRES"},
{"train_number":"12910","train_name":"BDTS GARIB RATH"},
{"train_number":"05034","train_name":""},
{"train_number":"02534","train_name":"HOLIDAY SPL"},
{"train_number":"01654","train_name":""},
{"train_number":"22915","train_name":"BDTS HSR SF EXP"},
{"train_number":"02915","train_name":""},
{"train_number":"09301","train_name":""},
{"train_number":"09029","train_name":""},
{"train_number":"11104","train_name":"BDTS JHANSI EXP"},
{"train_number":"22933","train_name":"BDTS JP SF EXP"},
{"train_number":"09033","train_name":""},
{"train_number":"09732","train_name":""},
{"train_number":"22931","train_name":"BDTS JSM EXP"},
{"train_number":"09063","train_name":""},
{"train_number":"19063","train_name":"DANAPUR EXPRESS"},
{"train_number":"09045","train_name":""},
{"train_number":"09019","train_name":""},
{"train_number":"22444","train_name":"BDTS KANPUR EXP"},
{"train_number":"19021","train_name":"BDTS LJN EXPRES"},
{"train_number":"09009","train_name":""},
{"train_number":"12247","train_name":"BDTS NZM YUVA E"},
{"train_number":"09561","train_name":""},
{"train_number":"19049","train_name":"BDTS PATNA EXP"},
{"train_number":"22935","train_name":"BDTS PIT SF EXP"},
{"train_number":"09011","train_name":""},
{"train_number":"09061","train_name":""},
{"train_number":"12907","train_name":"BDTS SMPRK K EX"},
{"train_number":"12935","train_name":"BDTS SURAT EXP"},
{"train_number":"14321","train_name":"BE BHUJ EXP"},
{"train_number":"14236","train_name":"BE BSB EXPRESS"},
{"train_number":"54077","train_name":"BE DLI PASSENGER"},
{"train_number":"14320","train_name":"BE INDB EXPRESS"},
{"train_number":"04314","train_name":""},
{"train_number":"14308","train_name":""},
{"train_number":"14314","train_name":"BE LTT EXPRESS"},
{"train_number":"04918","train_name":""},
{"train_number":"12237","train_name":"BEGAMPURA EXP"},
{"train_number":"12238","train_name":"BEGAMPURA EXP"},
{"train_number":"18203","train_name":"BETWA EXPRESS"},
{"train_number":"18204","train_name":"BETWA EXPRESS"},
{"train_number":"14803","train_name":"BGKT ADI EXPRES"},
{"train_number":"04803","train_name":""},
{"train_number":"09054","train_name":""},
{"train_number":"19066","train_name":"BGKT BDTS EXP"},
{"train_number":"18244","train_name":"BGKT BSP EXP"},
{"train_number":"08244","train_name":"BGKT BSP SPL"},
{"train_number":"15623","train_name":"BGKT KYQ EXP"},
{"train_number":"05623","train_name":""},
{"train_number":"16863","train_name":"BGKT MQ EXPRESS"},
{"train_number":"16533","train_name":"BGKT SBC EXPRES"},
{"train_number":"16507","train_name":"BGKT SBCEXP"},
{"train_number":"18574","train_name":"BGKT VSKP EXP"},
{"train_number":"11089","train_name":"BGKTPUNE EXPRES"},
{"train_number":"07327","train_name":""},
{"train_number":"22405","train_name":"BGP  GARIB RATH"},
{"train_number":"13423","train_name":"BGP AII EXPRESS"},
{"train_number":"03453","train_name":""},
{"train_number":"12335","train_name":"BGP LTT EXPRESS"},
{"train_number":"","train_name":""},
{"train_number":"12349","train_name":"BGP NDLS EXP"},
{"train_number":"03435","train_name":""},
{"train_number":"18604","train_name":"BGP RNC EXPRESS"},
{"train_number":"19048","train_name":"BGP SURAT EXP"},
{"train_number":"08104","train_name":""},
{"train_number":"12891","train_name":"BGY  BBS EXPRES"},
{"train_number":"12336","train_name":"BHAGALPUR EXP"},
{"train_number":"13104","train_name":"BHAGIRATHI EXP"},
{"train_number":"13103","train_name":"BHAGIRATHI EXP"},
{"train_number":"17233","train_name":"BHAGYANAGAR EXP"},
{"train_number":"17234","train_name":"BHAGYANAGAR EXP"},
{"train_number":"12971","train_name":"BHAVNAGAR EXP"},
{"train_number":"59208","train_name":"OKHA BVC PASSENGER"},
{"train_number":"59828","train_name":"ETW BIX PASSENGER"},
{"train_number":"12156","train_name":"BHOPAL  EXPRESS"},
{"train_number":"12155","train_name":"BHOPAL  EXPRESS"},
{"train_number":"59389","train_name":"INDB BPL PASSENGER"},
{"train_number":"12002","train_name":"BHOPAL SHTBDI"},
{"train_number":"13015","train_name":""},
{"train_number":"12846","train_name":"BHUBANESHWAR EX"},
{"train_number":"02846","train_name":""},
{"train_number":"18495","train_name":"BHUBANESWAR EXP"},
{"train_number":"12829","train_name":"BHUBANESWAR EXP"},
{"train_number":"22903","train_name":"BHUJ AC S F EXP"},
{"train_number":"19116","train_name":"BHUJ BDTS EXP"},
{"train_number":"09024","train_name":""},
{"train_number":"09458","train_name":"HOLIDAY SPL"},
{"train_number":"12960","train_name":"BHUJ DADAR EXP"},
{"train_number":"11091","train_name":"BHUJ PUNE EXP"},
{"train_number":"22829","train_name":"BHUJ SHM EXP"},
{"train_number":"59013","train_name":"ST BSL PASSENGER"},
{"train_number":"59075","train_name":"ST BSL PASSENGER"},
{"train_number":"59077","train_name":"ST BSL PASSENGER"},
{"train_number":"17009","train_name":""},
{"train_number":"11076","train_name":"BIDR LTT EXP"},
{"train_number":"16572","train_name":"BIDR YPR EXP"},
{"train_number":"12566","train_name":"BIHAR S KRANTI"},
{"train_number":"12565","train_name":"BIHAR S KRANTI"},
{"train_number":"01493","train_name":""},
{"train_number":"06535","train_name":""},
{"train_number":"22476","train_name":"BIKANER AC EXP"},
{"train_number":"06013","train_name":""},
{"train_number":"16312","train_name":"BIKANER EXPRESS"},
{"train_number":"","train_name":""},
{"train_number":"12852","train_name":"BILASPUR EXPRES"},
{"train_number":"12442","train_name":"BILASPUR RJDHNI"},
{"train_number":"","train_name":""},
{"train_number":"59822","train_name":"BIX KOTA PASSENGER"},
{"train_number":"51030","train_name":"BJP CSTM PASSENGER"},
{"train_number":"05285","train_name":""},
{"train_number":"15231","train_name":"BJU GONDIA EXP"},
{"train_number":"11123","train_name":"BJU GWL MAIL"},
{"train_number":"15203","train_name":"BJU LJN EXP"},
{"train_number":"05231","train_name":""},
{"train_number":"04021","train_name":""},
{"train_number":"04701","train_name":""},
{"train_number":"22631","train_name":"ANUVRATEXPRESS"},
{"train_number":"22473","train_name":"BKN BDTS SF EXP"},
{"train_number":"09008","train_name":""},
{"train_number":"04737","train_name":""},
{"train_number":"18246","train_name":"BKN BSP EXP"},
{"train_number":"08246","train_name":""},
{"train_number":"22475","train_name":"BKN CBE AC S F"},
{"train_number":"12489","train_name":"BKN DDR SF EXP"},
{"train_number":"04727","train_name":""},
{"train_number":"12458","train_name":"BKN DEE S F EXP"},
{"train_number":"04725","train_name":""},
{"train_number":"12456","train_name":"BKN DEE SF EXP"},
{"train_number":"25631","train_name":"BKN GHY EXPRESS"},
{"train_number":"04735","train_name":"HOLIDAY SPL"},
{"train_number":"22308","train_name":"BKN HWH SUPFAST"},
{"train_number":"22472","train_name":"BKN INTERCITY"},
{"train_number":"12467","train_name":"LEELAN EXP"},
{"train_number":"14702","train_name":""},
{"train_number":"22480","train_name":"BKN JSM EXPRESS"},
{"train_number":"16311","train_name":"BKN KCVL EXPRES"},
{"train_number":"12495","train_name":"BKN KOAA SUP EX"},
{"train_number":"22632","train_name":"ANUVRAT EXP"},
{"train_number":"06014","train_name":""},
{"train_number":"17624","train_name":"BKN NED EXP"},
{"train_number":"07409","train_name":""},
{"train_number":"07038","train_name":""},
{"train_number":"04739","train_name":""},
{"train_number":"14709","train_name":"BKN PURI EXP"},
{"train_number":"04741","train_name":""},
{"train_number":"17038","train_name":"BKN SC EXP"},
{"train_number":"04732","train_name":""},
{"train_number":"16588","train_name":"BKN YPR EXPRESS"},
{"train_number":"02692","train_name":""},
{"train_number":"06588","train_name":""},
{"train_number":"58014","train_name":"BKSC HWH PASSENGER"},
{"train_number":"09053","train_name":""},
{"train_number":"22909","train_name":"BL  PURI S F EX"},
{"train_number":"12583","train_name":"ANVT DOUBLE DKR"},
{"train_number":"04738","train_name":""},
{"train_number":"12911","train_name":"BL HARIDWAR EXP"},
{"train_number":"19055","train_name":"BL JODHPUR EXP"},
{"train_number":"19052","train_name":"BL SHRAMIK EXP"},
{"train_number":"09057","train_name":""},
{"train_number":"22388","train_name":"BLACKDIAMOND EX"},
{"train_number":"13318","train_name":""},
{"train_number":"13317","train_name":""},
{"train_number":"22387","train_name":"BLACKDIAMOND EX"},
{"train_number":"12893","train_name":"BLGR  EXPRESS"},
{"train_number":"13064","train_name":"BLGT HWH EXPRES"},
{"train_number":"13162","train_name":"BLGT KOAA EXP"},
{"train_number":"04973","train_name":""},
{"train_number":"15631","train_name":"BME GHY EXPRESS"},
{"train_number":"24888","train_name":"BME HW LINK EXP"},
{"train_number":"14806","train_name":"BME YPR AC EXP"},
{"train_number":"02509","train_name":""},
{"train_number":"02353","train_name":""},
{"train_number":"02659","train_name":""},
{"train_number":"02657","train_name":""},
{"train_number":"04724","train_name":"HOLIDAY SPL"},
{"train_number":"03174","train_name":""},
{"train_number":"57129","train_name":"BJP BMO PASSENGER"},
{"train_number":"13137","train_name":"KOAA AMH EXPRES"},
{"train_number":"17012","train_name":""},
{"train_number":"13118","train_name":"LGL KOAA EXPRES"},
{"train_number":"22186","train_name":"BPL DOUBLE DECK"},
{"train_number":"13026","train_name":"BPL HOWRAH EXP"},
{"train_number":"59390","train_name":"BPL INDB PASSENGER"},
{"train_number":"12198","train_name":"BPL INTERCITY"},
{"train_number":"19712","train_name":"BPL JAIPUR EXP"},
{"train_number":"54811","train_name":"BPL JU PASSENGER"},
{"train_number":"07620","train_name":""},
{"train_number":"01683","train_name":""},
{"train_number":"12183","train_name":"BPL PBH SUP EXP"},
{"train_number":"02183","train_name":""},
{"train_number":"59320","train_name":"BPL UJN PASSENGER"},
{"train_number":"51196","train_name":"BPQ WR PASSENGER"},
{"train_number":"14055","train_name":"BRAHMPUTRA MAIL"},
{"train_number":"14056","train_name":"BRAHMPUTRA MAIL"},
{"train_number":"19129","train_name":""},
{"train_number":"09457","train_name":"HOLIDAY SPL"},
{"train_number":"09058","train_name":""},
{"train_number":"12639","train_name":"BRINDAVAN EXP"},
{"train_number":"12640","train_name":"BRINDAVAN EXP"},
{"train_number":"51452","train_name":"BRMT PUNE PASSENGER"},
{"train_number":"19408","train_name":"BSB ADI EXP"},
{"train_number":"22407","train_name":"BSB ANVT G RATH"},
{"train_number":"14235","train_name":"BSB BE EXPRESS"},
{"train_number":"04911","train_name":"DBG UMB SPL"},
{"train_number":"04503","train_name":"HOLIDAY SPL"},
{"train_number":"04505","train_name":""},
{"train_number":"01030","train_name":""},
{"train_number":"01028","train_name":""},
{"train_number":"01080","train_name":""},
{"train_number":"14265","train_name":"BSB DDN EXP"},
{"train_number":"04203","train_name":""},
{"train_number":"04931","train_name":""},
{"train_number":"04205","train_name":""},
{"train_number":"22408","train_name":"BSB GARIB RATH"},
{"train_number":"14213","train_name":"BSB GD INTERCIT"},
{"train_number":"25652","train_name":""},
{"train_number":"05652","train_name":""},
{"train_number":"13346","train_name":"BSB INTERCITY E"},
{"train_number":"21108","train_name":"BSB KURJ LINK E"},
{"train_number":"14219","train_name":"BSB LKO EXP"},
{"train_number":"14203","train_name":"BSB LKO INTRCIT"},
{"train_number":"02070","train_name":""},
{"train_number":"01056","train_name":""},
{"train_number":"12168","train_name":"BSB LTT SUP EXP"},
{"train_number":"12166","train_name":"BSB LTT SUP EXP"},
{"train_number":"16230","train_name":"BSB MYS EXP"},
{"train_number":"02682","train_name":""},
{"train_number":"06230","train_name":""},
{"train_number":"04433","train_name":""},
{"train_number":"19570","train_name":"BSB OKHA EXP"},
{"train_number":"02069","train_name":""},
{"train_number":"14260","train_name":"EKATMATA EXPRES"},
{"train_number":"18612","train_name":"BSB RNC EXPRESS"},
{"train_number":"18312","train_name":"BSB SBP EXPRESS"},
{"train_number":"13134","train_name":"BSB SDAH EXPRES"},
{"train_number":"01075","train_name":""},
{"train_number":"19058","train_name":"BSB UDN EXP"},
{"train_number":"04209","train_name":""},
{"train_number":"22111","train_name":"BSL NGP SUP EXP"},
{"train_number":"11025","train_name":"BSL PUNE EXP"},
{"train_number":"59076","train_name":"BSL ST PASSENGER"},
{"train_number":"18243","train_name":"BSP BGKT EXPRES"},
{"train_number":"08243","train_name":"BSP BGKTSPECIAL"},
{"train_number":"18245","train_name":"BSP BKN EXPRESS"},
{"train_number":"08245","train_name":"BSP BKN SPECIAL"},
{"train_number":"18236","train_name":""},
{"train_number":"58219","train_name":"BSP CHRM PASSENGER"},
{"train_number":"22815","train_name":"BSP ERS S F EXP"},
{"train_number":"58210","train_name":"BSP GAD PASSENGER"},
{"train_number":"22940","train_name":"BSP HAPA EXPRES"},
{"train_number":"09536","train_name":""},
{"train_number":"12856","train_name":"BSP INTERCITY"},
{"train_number":"01754","train_name":""},
{"train_number":"01756","train_name":""},
{"train_number":"12851","train_name":"BSP MAS EXP"},
{"train_number":"12441","train_name":"BSP NDLS RAJ EX"},
{"train_number":"22843","train_name":"BSP PNBE EXP"},
{"train_number":"08293","train_name":""},
{"train_number":"08295","train_name":""},
{"train_number":"12849","train_name":"BSP PUNE SUP EX"},
{"train_number":"58229","train_name":"BSP REWA PASSENGER"},
{"train_number":"58114","train_name":"BSP TATA PASSENGER"},
{"train_number":"12787","train_name":""},
{"train_number":"22619","train_name":"BSP TEN EXPRESS"},
{"train_number":"17481","train_name":"BSP TPTY EXPRES"},
{"train_number":"00117","train_name":"HOLIDAY SPL"},
{"train_number":"58865","train_name":""},
{"train_number":"58871","train_name":""},
{"train_number":"04974","train_name":""},
{"train_number":"04010","train_name":""},
{"train_number":"19225","train_name":"BTI JAT EXP"},
{"train_number":"14501","train_name":"BTI JAT EXP"},
{"train_number":"54701","train_name":"BTI LGH PASSENGER"},
{"train_number":"12048","train_name":"BTI NDLS SHTBDI"},
{"train_number":"04514","train_name":""},
{"train_number":"22824","train_name":"BUBNESWR RJDHNI"},
{"train_number":"22812","train_name":"BUBNESWR RJDHNI"},
{"train_number":"15109","train_name":""},
{"train_number":"14223","train_name":"BUDH PURNIMA EX"},
{"train_number":"14224","train_name":"BUDHPURNIMA EXP"},
{"train_number":"15110","train_name":""},
{"train_number":"13106","train_name":"BUI SDAH EXP"},
{"train_number":"11107","train_name":"BUNDELKHAND EXP"},
{"train_number":"11108","train_name":"BUNDELKHAND EXP"},
{"train_number":"12941","train_name":"BVC ASANSOL EXP"},
{"train_number":"12972","train_name":"BVC BDTS EXPRES"},
{"train_number":"19204","train_name":"BVC BDTS EXPRES"},
{"train_number":"09232","train_name":""},
{"train_number":"59272","train_name":"BVC SUNR PASSENGER"},
{"train_number":"17203","train_name":"BVC KAKINADA EX"},
{"train_number":"19260","train_name":"BVC KCVL EXP"},
{"train_number":"59207","train_name":"BVC OKHA PASSENGER"},
{"train_number":"59230","train_name":"BVC ST LINK EXP"},
{"train_number":"18438","train_name":"BWIP BBS LINK E"},
{"train_number":"13013","train_name":""},
{"train_number":"59806","train_name":"BXN FL PASSENGER"},
{"train_number":"02714","train_name":""},
{"train_number":"56504","train_name":"BZA BNC PASSENGER"},
{"train_number":"12796","train_name":""},
{"train_number":"07213","train_name":""},
{"train_number":"07219","train_name":""},
{"train_number":"07204","train_name":""},
{"train_number":"07209","train_name":""},
{"train_number":"07207","train_name":""},
{"train_number":"17208","train_name":"BZA SNSI EXP"},
{"train_number":"12823","train_name":"C G  SMPRK KRNT"},
{"train_number":"15692","train_name":""},
{"train_number":"15691","train_name":""},
{"train_number":"16305","train_name":"CANNANORE EXP"},
{"train_number":"16313","train_name":"CANNANORE EXP"},
{"train_number":"16307","train_name":"CANNANORE EXP"},
{"train_number":"12666","train_name":"CAPE HOWRAH EXP"},
{"train_number":"16382","train_name":"CAPE MUMBAI EXP"},
{"train_number":"22622","train_name":"CAPE RMM EXP"},
{"train_number":"12790","train_name":""},
{"train_number":"13246","train_name":"CAPITAL EXP"},
{"train_number":"13245","train_name":"CAPITAL EXPRESS"},
{"train_number":"06630","train_name":""},
{"train_number":"06632","train_name":""},
{"train_number":"12969","train_name":"CBE JAIPUR EXP"},
{"train_number":"06626","train_name":""},
{"train_number":"00604","train_name":"ERS MAS SUVIDHA"},
{"train_number":"00606","train_name":""},
{"train_number":"06610","train_name":""},
{"train_number":"16612","train_name":"CBE TN LINK EXP"},
{"train_number":"06635","train_name":""},
{"train_number":"07239","train_name":""},
{"train_number":"07102","train_name":""},
{"train_number":"07201","train_name":""},
{"train_number":"02775","train_name":""},
{"train_number":"17206","train_name":"COA SNSI EXP"},
{"train_number":"17204","train_name":"COA BVC EXPRESS"},
{"train_number":"07338","train_name":""},
{"train_number":"07211","train_name":""},
{"train_number":"02737","train_name":""},
{"train_number":"19308","train_name":"CDG  INDB  EXP"},
{"train_number":"13256","train_name":"CDG  PPTA EXP"},
{"train_number":"12984","train_name":"CDG AII G RATH"},
{"train_number":"02411","train_name":""},
{"train_number":"12241","train_name":"CDG ASR SUP"},
{"train_number":"22452","train_name":"CDG BDTS SF EXP"},
{"train_number":"04512","train_name":""},
{"train_number":"04912","train_name":""},
{"train_number":"04506","train_name":""},
{"train_number":"04504","train_name":"HOLIDAY SPL"},
{"train_number":"05904","train_name":""},
{"train_number":"25904","train_name":""},
{"train_number":"15904","train_name":"CDG DBRG EXPRES"},
{"train_number":"04032","train_name":""},
{"train_number":"04507","train_name":""},
{"train_number":"09304","train_name":""},
{"train_number":"19718","train_name":"CDG JP INTERCIT"},
{"train_number":"04502","train_name":""},
{"train_number":"15012","train_name":"CDG LJN EXPRESS"},
{"train_number":"12232","train_name":"CDG LKO EXPRESS"},
{"train_number":"22688","train_name":"CDG MDU SF EXP"},
{"train_number":"12046","train_name":"CDG NDLS SHTBDI"},
{"train_number":"15032","train_name":"CDG RMR  EXP"},
{"train_number":"05056","train_name":""},
{"train_number":"04511","train_name":""},
{"train_number":"22451","train_name":"CDG SUP FAST"},
{"train_number":"06629","train_name":""},
{"train_number":"06631","train_name":""},
{"train_number":"06627","train_name":""},
{"train_number":"11006","train_name":"CHALUKYA  EXP"},
{"train_number":"11022","train_name":"CHALUKYA  EXP"},
{"train_number":"12177","train_name":"CHAMBAL EXP"},
{"train_number":"12175","train_name":"CHAMBAL EXP"},
{"train_number":"12176","train_name":"CHAMBAL EXPRESS"},
{"train_number":"12178","train_name":"CHAMBAL EXPRESS"},
{"train_number":"16215","train_name":"CHAMUNDI EXP"},
{"train_number":"16216","train_name":"CHAMUNDI EXPRES"},
{"train_number":"19307","train_name":"CHANDIGARH EXP"},
{"train_number":"09303","train_name":""},
{"train_number":"12760","train_name":"CHARMINAR EXP"},
{"train_number":"12759","train_name":"CHARMINAR EXP"},
{"train_number":"18237","train_name":"CHATTISGARH EXP"},
{"train_number":"15003","train_name":"CHAURICHAURAEXP"},
{"train_number":"15004","train_name":"CHAURICHAURAEXP"},
{"train_number":"58222","train_name":"CHD CHRM PASSENGER"},
{"train_number":"16616","train_name":"CHEMMOZHI EXP"},
{"train_number":"16615","train_name":"CHEMMOZHI EXP"},
{"train_number":"06060","train_name":""},
{"train_number":"06346","train_name":"HOLIDAY SPL"},
{"train_number":"06340","train_name":""},
{"train_number":"06348","train_name":""},
{"train_number":"06604","train_name":""},
{"train_number":"06608","train_name":""},
{"train_number":"06616","train_name":""},
{"train_number":"06062","train_name":""},
{"train_number":"06084","train_name":""},
{"train_number":"06082","train_name":""},
{"train_number":"12604","train_name":"CHENNAI EXP"},
{"train_number":"06624","train_name":""},
{"train_number":"06316","train_name":""},
{"train_number":"06016","train_name":""},
{"train_number":"06042","train_name":""},
{"train_number":"06018","train_name":""},
{"train_number":"06040","train_name":""},
{"train_number":"06004","train_name":""},
{"train_number":"06008","train_name":""},
{"train_number":"06006","train_name":""},
{"train_number":"06804","train_name":""},
{"train_number":"16176","train_name":"CHENNAI EXP"},
{"train_number":"06310","train_name":""},
{"train_number":"12164","train_name":"CHENNAI EXP"},
{"train_number":"06706","train_name":""},
{"train_number":"12682","train_name":"CHENNAI EXP"},
{"train_number":"06312","train_name":""},
{"train_number":"06606","train_name":"HOLIDAY SPL"},
{"train_number":"12686","train_name":"CHENNAI EXP"},
{"train_number":"12668","train_name":"CHENNAI EXP"},
{"train_number":"06338","train_name":""},
{"train_number":"06036","train_name":""},
{"train_number":"12163","train_name":"CHENNAI EXPRESS"},
{"train_number":"16702","train_name":""},
{"train_number":"22681","train_name":"CHENNAI EXPRESS"},
{"train_number":"12610","train_name":"CHENNAI EXPRESS"},
{"train_number":"06012","train_name":""},
{"train_number":"22640","train_name":"CHENNAI EXPRESS"},
{"train_number":"16042","train_name":""},
{"train_number":"06749","train_name":""},
{"train_number":"56101","train_name":"CHENNAI EXPRESS"},
{"train_number":"12680","train_name":"CHENNAI EXPRESS"},
{"train_number":"22624","train_name":"CHENNAI EXPRESS"},
{"train_number":"16854","train_name":"CHENNAI EXPRESS"},
{"train_number":"06748","train_name":""},
{"train_number":"12692","train_name":"CHENNAI EXPRESS"},
{"train_number":"06056","train_name":""},
{"train_number":"16102","train_name":"CHENNAI EXPRESS"},
{"train_number":"06058","train_name":""},
{"train_number":"06750","train_name":""},
{"train_number":"12794","train_name":""},
{"train_number":"11074","train_name":"CHENNAI LTT EXP"},
{"train_number":"12658","train_name":"CHENNAI MAIL"},
{"train_number":"11027","train_name":"CHENNAI MAIL"},
{"train_number":"12602","train_name":"CHENNAI MAIL"},
{"train_number":"12624","train_name":"CHENNAI MAIL"},
{"train_number":"12434","train_name":"CHENNAI RAJDHNI"},
{"train_number":"12673","train_name":"CHERAN EXPRESS"},
{"train_number":"12674","train_name":"CHERAN EXPRESS"},
{"train_number":"12981","train_name":"CHETAK EXP"},
{"train_number":"12982","train_name":"CHETAK EXP"},
{"train_number":"11059","train_name":"CHHAPRA EXPRESS"},
{"train_number":"18238","train_name":"CHHATISGARH EXP"},
{"train_number":"15205","train_name":"CHITRAKUT  EXP"},
{"train_number":"15009","train_name":""},
{"train_number":"15206","train_name":"CHITRAKUT EXP"},
{"train_number":"15010","train_name":""},
{"train_number":"58220","train_name":"CHRM BSP PASSENGER"},
{"train_number":"58221","train_name":"CHRM CHD PASSENGER"},
{"train_number":"51754","train_name":"CHRM REWA PASSENGER"},
{"train_number":"12824","train_name":"CHTSGRH S KRNTI"},
{"train_number":"17643","train_name":"CIRCAR EXP"},
{"train_number":"17644","train_name":"CIRCAR EXP"},
{"train_number":"18403","train_name":"CKP BBN INT EXP"},
{"train_number":"08463","train_name":""},
{"train_number":"58012","train_name":"CKP HWH PASSENGER"},
{"train_number":"14151","train_name":"CNB ANVT EXP"},
{"train_number":"14153","train_name":"CNB ASR EXP"},
{"train_number":"22443","train_name":"CNB BDTS SF"},
{"train_number":"04723","train_name":"HOLIDAY SPL"},
{"train_number":"04153","train_name":""},
{"train_number":"12210","train_name":"CNB GARIB RATH"},
{"train_number":"22441","train_name":""},
{"train_number":"12469","train_name":"CNB JAT EXPRESS"},
{"train_number":"02451","train_name":""},
{"train_number":"12033","train_name":"CNB NDLS SHT"},
{"train_number":"","train_name":""},
{"train_number":"17221","train_name":"COA  LTT EXPRES"},
{"train_number":"12339","train_name":"COAL FIELD EXP"},
{"train_number":"12340","train_name":"COALFIELD EXP"},
{"train_number":"12775","train_name":"COCANADA EXP"},
{"train_number":"12776","train_name":"COCANADA EXP"},
{"train_number":"12679","train_name":"COIMBATORE EXP"},
{"train_number":"16617","train_name":"COIMBATORE EXP"},
{"train_number":"11013","train_name":"COIMBATORE EXP"},
{"train_number":"06605","train_name":""},
{"train_number":"16613","train_name":"COIMBATORE EXP"},
{"train_number":"06037","train_name":""},
{"train_number":"06603","train_name":""},
{"train_number":"06607","train_name":"HOLIDAY SPL"},
{"train_number":"06636","train_name":""},
{"train_number":"06615","train_name":""},
{"train_number":"06618","train_name":""},
{"train_number":"06009","train_name":""},
{"train_number":"06634","train_name":""},
{"train_number":"06039","train_name":""},
{"train_number":"12681","train_name":"COIMBATORE EXP"},
{"train_number":"16609","train_name":"COIMBATORE EXP"},
{"train_number":"25014","train_name":"CORBET PRK LINK"},
{"train_number":"12841","train_name":"COROMANDAL EXP"},
{"train_number":"12842","train_name":"COROMANDEL EXP"},
{"train_number":"05103","train_name":""},
{"train_number":"15115","train_name":"LOK NAYAK EXP"},
{"train_number":"15117","train_name":"MUV JBP EXPRES"},
{"train_number":"15112","train_name":"CPR INTERCITY"},
{"train_number":"15106","train_name":""},
{"train_number":"05143","train_name":""},
{"train_number":"15053","train_name":"CPR LJN EXP"},
{"train_number":"05065","train_name":"HOLIDAY SPL"},
{"train_number":"05115","train_name":""},
{"train_number":"11060","train_name":"CPR LTT EXPRESS"},
{"train_number":"15107","train_name":"CPR MTJ EXPRESS"},
{"train_number":"18182","train_name":"CPR TATA EXP"},
{"train_number":"08182","train_name":""},
{"train_number":"01065","train_name":""},
{"train_number":"02004","train_name":""},
{"train_number":"12111","train_name":"CSTM AMRAVATI E"},
{"train_number":"12362","train_name":"CSTM ASANSOL EX"},
{"train_number":"01027","train_name":""},
{"train_number":"01079","train_name":""},
{"train_number":"11041","train_name":"CSTM CHENNAI EX"},
{"train_number":"51034","train_name":"SNSI CSTM PASSENGER"},
{"train_number":"01034","train_name":"HOLIDAY SPL"},
{"train_number":"02187","train_name":""},
{"train_number":"02083","train_name":""},
{"train_number":"01087","train_name":""},
{"train_number":"02041","train_name":""},
{"train_number":"02171","train_name":"JAT SUVIDHA SPL"},
{"train_number":"01701","train_name":""},
{"train_number":"04154","train_name":""},
{"train_number":"22107","train_name":"CSTM LATUR EXP"},
{"train_number":"12527","train_name":""},
{"train_number":"01019","train_name":""},
{"train_number":"01051","train_name":""},
{"train_number":"01033","train_name":"HOLIDAY SPL"},
{"train_number":"01211","train_name":"HOLIDAY SPL"},
{"train_number":"01013","train_name":""},
{"train_number":"02008","train_name":""},
{"train_number":"02702","train_name":""},
{"train_number":"02002","train_name":""},
{"train_number":"11305","train_name":"CSTM SOLAPUR EX"},
{"train_number":"12959","train_name":"DADAR BHUJ EXP"},
{"train_number":"22629","train_name":"DADAR TEN EXP"},
{"train_number":"12722","train_name":"DAKSHIN EXPRESS"},
{"train_number":"12351","train_name":"DANAPUR EXPRESS"},
{"train_number":"12352","train_name":"RJPB HWH EXPRES"},
{"train_number":"11065","train_name":"DARBHANGA  EXP"},
{"train_number":"","train_name":""},
{"train_number":"11033","train_name":"DARBHANGA EXP"},
{"train_number":"12344","train_name":"DARJEELING MAIL"},
{"train_number":"12343","train_name":"DARJEELING MAIL"},
{"train_number":"14035","train_name":"DAULADHAR EXP"},
{"train_number":"57515","train_name":"DD NED PASSENGER"},
{"train_number":"12182","train_name":"DAYODAYA EXP"},
{"train_number":"12181","train_name":"DAYODAYA EXPRES"},
{"train_number":"05818","train_name":"HOLIDAY SPL"},
{"train_number":"05917","train_name":""},
{"train_number":"15817","train_name":"DBB SHTT RR EXP"},
{"train_number":"05237","train_name":""},
{"train_number":"05213","train_name":""},
{"train_number":"04023","train_name":""},
{"train_number":"04409","train_name":""},
{"train_number":"15236","train_name":"DBG HWH EXPRESS"},
{"train_number":"17006","train_name":"DBG HYB EXPRESS"},
{"train_number":"15234","train_name":"DBG KOAA EXPRES"},
{"train_number":"11066","train_name":"DBG LTT EXPRESS"},
{"train_number":"02050","train_name":"GATIMAAN INAGRL"},
{"train_number":"04071","train_name":""},
{"train_number":"04410","train_name":""},
{"train_number":"04024","train_name":""},
{"train_number":"11034","train_name":"DBG PUNE EXP"},
{"train_number":"17008","train_name":"DBG SC EXPRESS"},
{"train_number":"05215","train_name":""},
{"train_number":"05287","train_name":""},
{"train_number":"05942","train_name":""},
{"train_number":"15905","train_name":"DBRG  VIVEK EXP"},
{"train_number":"15933","train_name":"DBRG ASR EXPRES"},
{"train_number":"15903","train_name":"DBRG CDG EXPRES"},
{"train_number":"25903","train_name":""},
{"train_number":"05903","train_name":""},
{"train_number":"05918","train_name":""},
{"train_number":"05933","train_name":""},
{"train_number":"05970","train_name":""},
{"train_number":"15942","train_name":"DBRG JHAJHA EXP"},
{"train_number":"12526","train_name":"DBRG KOAA EXP"},
{"train_number":"05668","train_name":""},
{"train_number":"15930","train_name":"DBRG MS EXPRESS"},
{"train_number":"05606","train_name":""},
{"train_number":"12235","train_name":"DBRG NDLS RAJEX"},
{"train_number":"15928","train_name":"DBRG RNY EXPRES"},
{"train_number":"05968","train_name":"HOLIDAY SPL"},
{"train_number":"15902","train_name":"NTSK SBC EXPRES"},
{"train_number":"05906","train_name":""},
{"train_number":"02423","train_name":""},
{"train_number":"12424","train_name":"DBRT RAJDHANI"},
{"train_number":"12423","train_name":"DBRT RAJDHANI E"},
{"train_number":"12435","train_name":"DBRT RAJDHANI E"},
{"train_number":"01303","train_name":""},
{"train_number":"01301","train_name":""},
{"train_number":"04054","train_name":""},
{"train_number":"14631","train_name":"DDN ASR EXPRESS"},
{"train_number":"14266","train_name":"DDN BSB EXPRESS"},
{"train_number":"15006","train_name":"DDN GKP EXP"},
{"train_number":"14631","train_name":"DDN ASR EXPRESS"},
{"train_number":"14318","train_name":"DDN INDB EXP"},
{"train_number":"14266","train_name":"DDN BSB EXPRESS"},
{"train_number":"15006","train_name":"DDN GKP EXP"},
{"train_number":"12055","train_name":"DDN JANSHTBDI"},
{"train_number":"12288","train_name":""},
{"train_number":"22660","train_name":"DDN KCVL SUP EX"},
{"train_number":"14120","train_name":"DDN KGM EXPRESS"},
{"train_number":"12688","train_name":"DDN MDU SF EXP"},
{"train_number":"15002","train_name":"DDN MFP EXP"},
{"train_number":"12490","train_name":"DDR BIKANER EXP"},
{"train_number":"14318","train_name":"DDN INDB EXP"},
{"train_number":"04728","train_name":""},
{"train_number":"11007","train_name":"DECCAN EXPRESS"},
{"train_number":"11008","train_name":"DECCAN EXPRESS"},
{"train_number":"12124","train_name":"DECCAN QUEEN"},
{"train_number":"12123","train_name":"DECCAN QUEEN"},
{"train_number":"09418","train_name":""},
{"train_number":"22920","train_name":""},
{"train_number":"09628","train_name":"HOLIDAY SPL"},
{"train_number":"19030","train_name":"DEE BDTS EXP"},
{"train_number":"12055","train_name":"DDN JANSHTBDI"},
{"train_number":"12288","train_name":""},
{"train_number":"12215","train_name":"DEE BDTS G RATH"},
{"train_number":"12457","train_name":"DEE BKN  S F EX"},
{"train_number":"04726","train_name":""},
{"train_number":"22660","train_name":"DDN KCVL SUP EX"},
{"train_number":"12455","train_name":"DEE BKN SF EXP"},
{"train_number":"14120","train_name":"DDN KGM EXPRESS"},
{"train_number":"12985","train_name":"DEE DOUBLE DCKE"},
{"train_number":"22985","train_name":""},
{"train_number":"04812","train_name":""},
{"train_number":"12688","train_name":"DDN MDU SF EXP"},
{"train_number":"15002","train_name":"DDN MFP EXP"},
{"train_number":"12490","train_name":"DDR BIKANER EXP"},
{"train_number":"12216","train_name":"DEE GARIBRATH"},
{"train_number":"04728","train_name":""},
{"train_number":"11007","train_name":"DECCAN EXPRESS"},
{"train_number":"14626","train_name":"DEE INTERCITY"},
{"train_number":"11008","train_name":"DECCAN EXPRESS"},
{"train_number":"12124","train_name":"DECCAN QUEEN"},
{"train_number":"22471","train_name":"DEE INTERCITY"},
{"train_number":"12123","train_name":"DECCAN QUEEN"},
{"train_number":"12265","train_name":"DEE JAT DURONTO"},
{"train_number":"09418","train_name":""},
{"train_number":"09706","train_name":""},
{"train_number":"22920","train_name":""},
{"train_number":"09628","train_name":"HOLIDAY SPL"},
{"train_number":"19030","train_name":"DEE BDTS EXP"},
{"train_number":"22482","train_name":"DEE JU SUP"},
{"train_number":"12215","train_name":"DEE BDTS G RATH"},
{"train_number":"12457","train_name":"DEE BKN  S F EX"},
{"train_number":"04026","train_name":""},
{"train_number":"04726","train_name":""},
{"train_number":"19264","train_name":"DEE PORBNDR EXP"},
{"train_number":"12455","train_name":"DEE BKN SF EXP"},
{"train_number":"09742","train_name":""},
{"train_number":"12985","train_name":"DEE DOUBLE DCKE"},
{"train_number":"22985","train_name":""},
{"train_number":"19580","train_name":"DEE RJT EXP"},
{"train_number":"04812","train_name":""},
{"train_number":"09580","train_name":""},
{"train_number":"14812","train_name":"DEE SIKAR EXP"},
{"train_number":"14705","train_name":"DEE BGKT EXP"},
{"train_number":"12216","train_name":"DEE GARIBRATH"},
{"train_number":"22401","train_name":"DEE UHP AC SUP"},
{"train_number":"14626","train_name":"DEE INTERCITY"},
{"train_number":"22471","train_name":"DEE INTERCITY"},
{"train_number":"12265","train_name":"DEE JAT DURONTO"},
{"train_number":"09706","train_name":""},
{"train_number":"22482","train_name":"DEE JU SUP"},
{"train_number":"04026","train_name":""},
{"train_number":"19264","train_name":"DEE PORBNDR EXP"},
{"train_number":"09742","train_name":""},
{"train_number":"04035","train_name":""},
{"train_number":"22659","train_name":"DEHRADUN EXP"},
{"train_number":"19580","train_name":"DEE RJT EXP"},
{"train_number":"09580","train_name":""},
{"train_number":"19020","train_name":"DEHRADUN EXP"},
{"train_number":"14812","train_name":"DEE SIKAR EXP"},
{"train_number":"14705","train_name":"DEE BGKT EXP"},
{"train_number":"22401","train_name":"DEE UHP AC SUP"},
{"train_number":"12687","train_name":"DEHRADUN EXP"},
{"train_number":"04035","train_name":""},
{"train_number":"22659","train_name":"DEHRADUN EXP"},
{"train_number":"19019","train_name":"DEHRADUN EXP"},
{"train_number":"12287","train_name":""},
{"train_number":"19020","train_name":"DEHRADUN EXP"},
{"train_number":"12687","train_name":"DEHRADUN EXP"},
{"train_number":"19019","train_name":"DEHRADUN EXP"},
{"train_number":"29020","train_name":"DEHRADUN EXPRES"},
{"train_number":"12287","train_name":""},
{"train_number":"12017","train_name":"DEHRADUN SHTBDI"},
{"train_number":"29020","train_name":"DEHRADUN EXPRES"},
{"train_number":"12018","train_name":"DEHRADUN SHTBDI"},
{"train_number":"12017","train_name":"DEHRADUN SHTBDI"},
{"train_number":"22919","train_name":""},
{"train_number":"19263","train_name":"DELHI SR EXPRES"},
{"train_number":"17058","train_name":"DEVAGIRI EXP"},
{"train_number":"17057","train_name":"DEVAGIRI EXP"},
{"train_number":"05421","train_name":""},
{"train_number":"12848","train_name":"HWH SUP AC EXP"},
{"train_number":"02250","train_name":""},
{"train_number":"13417","train_name":"DGHA MLDT EXP"},
{"train_number":"22877","train_name":"DGHA PURI EXP"},
{"train_number":"12579","train_name":""},
{"train_number":"22889","train_name":"DGHA PURI SUP E"},
{"train_number":"22873","train_name":"DGHA VSKP EXP"},
{"train_number":"13352","train_name":"DHANBAD EXPRESS"},
{"train_number":"14036","train_name":"DHAULADHAR EXP"},
{"train_number":"12822","train_name":"DHAULI EXP"},
{"train_number":"12821","train_name":"DHAULI EXP"},
{"train_number":"59393","train_name":"DHD HBJ PASSENGER"},
{"train_number":"13351","train_name":"DHN ALAPPUZHA E"},
{"train_number":"12832","train_name":"DHN GARIB RATH"},
{"train_number":"12386","train_name":""},
{"train_number":"13331","train_name":"DHN PNBE EXPRES"},
{"train_number":"03303","train_name":""},
{"train_number":"03327","train_name":""},
{"train_number":"15901","train_name":"NEW TINSUKIA EX"},
{"train_number":"05905","train_name":""},
{"train_number":"15929","train_name":"DIBRUGARH EXP"},
{"train_number":"11045","train_name":"DIKSHABHOOMI EX"},
{"train_number":"11046","train_name":"DIKSHABHUMI EXP"},
{"train_number":"50105","train_name":"DIVA SWV PASSENGER"},
{"train_number":"52544","train_name":"DJ KGN NG TRAIN"},
{"train_number":"52588","train_name":"DJ KGN NG TRAIN"},
{"train_number":"52540","train_name":"DJ NJP PASSENGE"},
{"train_number":"","train_name":""},
{"train_number":"04041","train_name":""},
{"train_number":"04204","train_name":""},
{"train_number":"04932","train_name":""},
{"train_number":"04413","train_name":""},
{"train_number":"13120","train_name":"DLI  SDAH EXP"},
{"train_number":"04002","train_name":""},
{"train_number":"14001","train_name":"DLI ATTARI EXP"},
{"train_number":"54078","train_name":"DLI BE PASSENGER"},
{"train_number":"04206","train_name":""},
{"train_number":"04432","train_name":""},
{"train_number":"04031","train_name":""},
{"train_number":"15116","train_name":"LOK NAYAK EXP"},
{"train_number":"05934","train_name":""},
{"train_number":"14206","train_name":"DLI FD EXP"},
{"train_number":"14731","train_name":"DLI FKA EXP"},
{"train_number":"03686","train_name":""},
{"train_number":"14011","train_name":"DLI HSX EXP"},
{"train_number":"04057","train_name":""},
{"train_number":"14659","train_name":"DLI JSM EXPRESS"},
{"train_number":"04438","train_name":""},
{"train_number":"04037","train_name":""},
{"train_number":"14037","train_name":"DLI PTK EXP"},
{"train_number":"04411","train_name":""},
{"train_number":"14521","train_name":"DLI UMB EXP"},
{"train_number":"52576","train_name":""},
{"train_number":"04853","train_name":""},
{"train_number":"03402","train_name":""},
{"train_number":"13247","train_name":"RJPB CAPITAL EX"},
{"train_number":"83112","train_name":""},
{"train_number":"83132","train_name":"DNR GRD LINK EX"},
{"train_number":"03236","train_name":""},
{"train_number":"23226","train_name":"SHC LINK EXPRES"},
{"train_number":"18184","train_name":"DNR TATA EXP"},
{"train_number":"13009","train_name":"DOON EXPRESS"},
{"train_number":"13010","train_name":"DOON EXPRESS"},
{"train_number":"23010","train_name":"DOON EXXPRESS"},
{"train_number":"13244","train_name":""},
{"train_number":"12131","train_name":"DR SAINAGAR EXP"},
{"train_number":"01003","train_name":""},
{"train_number":"18209","train_name":"DRZ R EXPRESS"},
{"train_number":"18620","train_name":"DUMK RNC EXPRES"},
{"train_number":"18241","train_name":""},
{"train_number":"18207","train_name":"DURG AII EXP"},
{"train_number":"18215","train_name":"DURG JAT EXPRES"},
{"train_number":"12549","train_name":"DURG JAT SF EXP"},
{"train_number":"01708","train_name":"HOLIDAY SPL"},
{"train_number":"18211","train_name":"DURG JDB EXP"},
{"train_number":"18213","train_name":"DURG JP EXP"},
{"train_number":"09718","train_name":""},
{"train_number":"18205","train_name":"DURG NTV EXP"},
{"train_number":"18201","train_name":"DURG NTV EXP"},
{"train_number":"03287","train_name":""},
{"train_number":"08798","train_name":""},
{"train_number":"18426","train_name":"DURG PURI EXP"},
{"train_number":"08202","train_name":""},
{"train_number":"58529","train_name":"DURG VSKP PASSENGER"},
{"train_number":"12357","train_name":"DURGIANA EXP"},
{"train_number":"12220","train_name":"DURONTO AC EXP"},
{"train_number":"22202","train_name":"DURONTO EXPRESS"},
{"train_number":"12246","train_name":"DURONTO EXPRESS"},
{"train_number":"22214","train_name":"DURONTO EXPRESS"},
{"train_number":"12266","train_name":"DURONTO EXPRESS"},
{"train_number":"12269","train_name":"DURONTO EXPRESS"},
{"train_number":"12213","train_name":"DURONTO EXPRESS"},
{"train_number":"22201","train_name":"DURONTO EXPRESS"},
{"train_number":"09726","train_name":"HOLIDAY SPL"},
{"train_number":"15636","train_name":"DWARKA  EXPRESS"},
{"train_number":"17302","train_name":"DWR MYSORE EXP"},
{"train_number":"56904","train_name":"DWR SUR PASSENGER"},
{"train_number":"18646","train_name":"EAST COAST EXP"},
{"train_number":"18645","train_name":"EAST COAST EXP"},
{"train_number":"16605","train_name":"ERNAD EXPRESS"},
{"train_number":"16606","train_name":"ERNAD EXPRESS"},
{"train_number":"12677","train_name":"ERNAKULAM EXP"},
{"train_number":"16314","train_name":"ERNAKULAM EXP"},
{"train_number":"16865","train_name":""},
{"train_number":"16187","train_name":"ERNAKULAM EXP"},
{"train_number":"16306","train_name":"ERNAKULAM EXP"},
{"train_number":"12684","train_name":"ERNAKULAM SF EX"},
{"train_number":"22608","train_name":"ERNAKULAM SF EX"},
{"train_number":"06055","train_name":""},
{"train_number":"06345","train_name":"HOLIDAY SPL"},
{"train_number":"22816","train_name":"ERS BILASPUR EX"},
{"train_number":"16188","train_name":"ERS KARAIKALEXP"},
{"train_number":"16866","train_name":""},
{"train_number":"01066","train_name":""},
{"train_number":"12224","train_name":"ERS LTT DURONTO"},
{"train_number":"12646","train_name":"ERS MILLENUM EX"},
{"train_number":"12283","train_name":"ERS NZM DURONTO"},
{"train_number":"16359","train_name":"ERS PATNA EXP"},
{"train_number":"22149","train_name":"ERS PUNE EXPRES"},
{"train_number":"02854","train_name":"02854 ERS-HWH SFSUVIDAH SPECIAL"},
{"train_number":"06549","train_name":""},
{"train_number":"59827","train_name":"BIX ETW PASSENGER"},
{"train_number":"12704","train_name":"FALAKNUMA EXP"},
{"train_number":"12703","train_name":"FALAKNUMA EXP"},
{"train_number":"13413","train_name":"FARAKKA EXPRESS"},
{"train_number":"13483","train_name":"FARAKKA EXPRESS"},
{"train_number":"13484","train_name":"FARAKKA EXPRESS"},
{"train_number":"13414","train_name":"FARKKA EXPRESS"},
{"train_number":"51028","train_name":"PVR CSTM PASSENGER"},
{"train_number":"51027","train_name":"CSTM PVR PASSENGER"},
{"train_number":"14205","train_name":"FD DLI EXP"},
{"train_number":"22104","train_name":"FD LTT SF EXP"},
{"train_number":"14732","train_name":"FKA DLI EXP"},
{"train_number":"04811","train_name":""},
{"train_number":"09770","train_name":""},
{"train_number":"12921","train_name":"FLYING RANEE"},
{"train_number":"12922","train_name":"FLYING RANEE"},
{"train_number":"04508","train_name":""},
{"train_number":"07138","train_name":""},
{"train_number":"19024","train_name":"FZR BCT JANTA"},
{"train_number":"04740","train_name":""},
{"train_number":"14625","train_name":"FZR INTERCITY"},
{"train_number":"19023","train_name":"FZR JANATA EXP"},
{"train_number":"05718","train_name":""},
{"train_number":"05216","train_name":""},
{"train_number":"08891","train_name":""},
{"train_number":"08897","train_name":""},
{"train_number":"08297","train_name":""},
{"train_number":"12616","train_name":"G T EXPRESS"},
{"train_number":"58209","train_name":"GAD BSP PASSENGER"},
{"train_number":"18239","train_name":"GAD NGP EXP"},
{"train_number":"13017","train_name":"GANADEVTA EXP"},
{"train_number":"13018","train_name":"GANADEVTA EXP"},
{"train_number":"19451","train_name":"GANDHIDHAM EXP"},
{"train_number":"16336","train_name":"GANDHIDHAM EXP"},
{"train_number":"16506","train_name":"GANDHIDHAM EXP"},
{"train_number":"19151","train_name":""},
{"train_number":"09451","train_name":""},
{"train_number":"09456","train_name":""},
{"train_number":"14216","train_name":"GANGA GOMTI EXP"},
{"train_number":"14215","train_name":"GANGA GOMTI EXP"},
{"train_number":"13186","train_name":"GANGA SAGAR EXP"},
{"train_number":"13329","train_name":"GANGADAMODAR EX"},
{"train_number":"13330","train_name":"GANGADAMODAR EX"},
{"train_number":"12670","train_name":"GANGAKAVERI EXP"},
{"train_number":"12669","train_name":"GANGAKAVERI EXP"},
{"train_number":"13185","train_name":"GANGASAGAR EXP"},
{"train_number":"13308","train_name":"GANGASATLUJ EXP"},
{"train_number":"13307","train_name":"GANGASUTLEJ EXP"},
{"train_number":"12938","train_name":"GARBHA EXPRESS"},
{"train_number":"12937","train_name":"GARBHA EXPRESS"},
{"train_number":"14044","train_name":"GARHWAL EXPRESS"},
{"train_number":"14043","train_name":"GARHWAL EXPRESS"},
{"train_number":"15716","train_name":"GARIB NAWAJ EXP"},
{"train_number":"15715","train_name":"GARIB NAWAJ EXP"},
{"train_number":"16532","train_name":"GARIB NAWAZ EXP"},
{"train_number":"14605","train_name":""},
{"train_number":"12203","train_name":"GARIB RATH EXP"},
{"train_number":"14606","train_name":""},
{"train_number":"","train_name":""},
{"train_number":"12049","train_name":"GATIMAAN EXP"},
{"train_number":"02397","train_name":""},
{"train_number":"03685","train_name":""},
{"train_number":"01660","train_name":""},
{"train_number":"13024","train_name":"GAYA HWH EXPRES"},
{"train_number":"01710","train_name":""},
{"train_number":"15619","train_name":"GAYA KYQ WKLY E"},
{"train_number":"12389","train_name":"GAYA MS EXPRESS"},
{"train_number":"13510","train_name":"GD ASN EXPRESS"},
{"train_number":"14214","train_name":"GD BSB INTERCIT"},
{"train_number":"11111","train_name":"GD SUSHASAN EXP"},
{"train_number":"","train_name":""},
{"train_number":"02424","train_name":""},
{"train_number":"15632","train_name":"GHY BME BKN EXP"},
{"train_number":"05653","train_name":""},
{"train_number":"25653","train_name":""},
{"train_number":"05969","train_name":""},
{"train_number":"12517","train_name":"GHY GARIB RATH"},
{"train_number":"05609","train_name":""},
{"train_number":"03058","train_name":""},
{"train_number":"25640","train_name":""},
{"train_number":"02502","train_name":""},
{"train_number":"05640","train_name":""},
{"train_number":"15606","train_name":"GHY INTERCITY"},
{"train_number":"25610","train_name":""},
{"train_number":"06335","train_name":"HOLIDAY SPL"},
{"train_number":"02518","train_name":""},
{"train_number":"15646","train_name":"GHY LTT EXP"},
{"train_number":"15648","train_name":"GHY LTT EXPRESS"},
{"train_number":"02435","train_name":""},
{"train_number":"02235","train_name":""},
{"train_number":"15617","train_name":"GHY NHLN I C EX"},
{"train_number":"02261","train_name":""},
{"train_number":"15640","train_name":"GHY PURI EXPRES"},
{"train_number":"22424","train_name":""},
{"train_number":"22423","train_name":""},
{"train_number":"12510","train_name":"GHY BNC EXPRESS"},
{"train_number":"12514","train_name":"GHY SC EXPRESS"},
{"train_number":"07250","train_name":""},
{"train_number":"07150","train_name":""},
{"train_number":"55615","train_name":"GHY SCL PASSENGER"},
{"train_number":"02262","train_name":""},
{"train_number":"12508","train_name":"GHY TVC EXPRESS"},
{"train_number":"12516","train_name":"GHY TVC EXPRESS"},
{"train_number":"09455","train_name":""},
{"train_number":"12993","train_name":"GIMB PURI EXP"},
{"train_number":"19453","train_name":"GIMB PURI EXP"},
{"train_number":"16505","train_name":"GIMB SBC EXPRES"},
{"train_number":"18502","train_name":"GIMB VSKP EXP"},
{"train_number":"12859","train_name":"GITANJALI EXP"},
{"train_number":"12860","train_name":"GITANJALI EXP"},
{"train_number":"19410","train_name":"GKP ADI EXP"},
{"train_number":"15057","train_name":"GKP ANVT EXP"},
{"train_number":"05039","train_name":""},
{"train_number":"05035","train_name":""},
{"train_number":"05027","train_name":""},
{"train_number":"05037","train_name":""},
{"train_number":"05057","train_name":""},
{"train_number":"05049","train_name":""},
{"train_number":"05051","train_name":""},
{"train_number":"13508","train_name":"GKP ASN EXPRESS"},
{"train_number":"02533","train_name":"HOLIDAY SPL"},
{"train_number":"05033","train_name":""},
{"train_number":"03454","train_name":""},
{"train_number":"01078","train_name":"HOLIDAY SPL"},
{"train_number":"15005","train_name":"GKP DDN EXPRESS"},
{"train_number":"05610","train_name":""},
{"train_number":"15104","train_name":"GKP INTERCITY"},
{"train_number":"15020","train_name":""},
{"train_number":"12532","train_name":"GKP INTERCITY"},
{"train_number":"15105","train_name":""},
{"train_number":"02529","train_name":""},
{"train_number":"05043","train_name":""},
{"train_number":"03132","train_name":"GKP ASN  SPL"},
{"train_number":"03136","train_name":""},
{"train_number":"15050","train_name":"GKP KOLKATA EXP"},
{"train_number":"15052","train_name":"GKP KOLKATA EXP"},
{"train_number":"15018","train_name":"GKP LTT EXP"},
{"train_number":"11082","train_name":"GKP LTT EXP"},
{"train_number":"11080","train_name":"GKP LTT EXPRESS"},
{"train_number":"02018","train_name":""},
{"train_number":"02016","train_name":""},
{"train_number":"01048","train_name":"HOLIDAY SPL"},
{"train_number":"05031","train_name":""},
{"train_number":"05041","train_name":""},
{"train_number":"12541","train_name":"GKP LTT SUP EXP"},
{"train_number":"55149","train_name":"GKP BCY PASSENGER"},
{"train_number":"15045","train_name":"GKP OKHA EXPRES"},
{"train_number":"02015","train_name":""},
{"train_number":"02528","train_name":""},
{"train_number":"02017","train_name":""},
{"train_number":"15029","train_name":"GKP PUNE EXP"},
{"train_number":"11038","train_name":"GKP PUNE EXPRES"},
{"train_number":"05023","train_name":""},
{"train_number":"12589","train_name":"GKP SC EXPRESS"},
{"train_number":"15022","train_name":"GKP SHM EXPRESS"},
{"train_number":"15023","train_name":"GKP YPR EXP"},
{"train_number":"12591","train_name":"GKP YPR EXPRESS"},
{"train_number":"15015","train_name":"GKP YPR EXPRESS"},
{"train_number":"19309","train_name":"GNC INDORE EXP"},
{"train_number":"22118","train_name":"GNT DOUBLE DECK"},
{"train_number":"57306","train_name":"GNT KCG PASSENGER"},
{"train_number":"12705","train_name":"GNT SC EXP"},
{"train_number":"07229","train_name":""},
{"train_number":"12779","train_name":"GOA EXPRESS"},
{"train_number":"12780","train_name":"GOA EXPRESS"},
{"train_number":"12449","train_name":"GOA SMPRK K EXP"},
{"train_number":"12450","train_name":"GOA SMPRK K EXP"},
{"train_number":"11055","train_name":"GODAN EXPRESS"},
{"train_number":"11056","train_name":"GODAN EXPRESS"},
{"train_number":"12728","train_name":"GODAVARI EXP"},
{"train_number":"12727","train_name":"GODAVARI EXP"},
{"train_number":"15315","train_name":"GOKUL EXP"},
{"train_number":"15316","train_name":"GOKUL EXPRESS"},
{"train_number":"17201","train_name":"GOLCONDA EXP"},
{"train_number":"17202","train_name":"GOLCONDA EXP"},
{"train_number":"12903","train_name":"GOLDENTEMPLE ML"},
{"train_number":"12904","train_name":"GOLDN TEMPLE ML"},
{"train_number":"16535","train_name":"GOLGUMBAZ EXP"},
{"train_number":"16536","train_name":"GOLGUMBAZ EXP"},
{"train_number":"12419","train_name":"GOMTI EXP"},
{"train_number":"12420","train_name":"GOMTI EXPRESS"},
{"train_number":"15232","train_name":"GONDIA BJU EXP"},
{"train_number":"15118","train_name":"JBP MUV EXPRESS"},
{"train_number":"12405","train_name":"GONDWANA EXPRES"},
{"train_number":"12409","train_name":"GONDWANA EXPRES"},
{"train_number":"12406","train_name":"GONDWANA EXPRES"},
{"train_number":"12410","train_name":"GONDWANA EXPRES"},
{"train_number":"12555","train_name":"GORAKDAM EXPRES"},
{"train_number":"12556","train_name":"GORAKDAM EXPRES"},
{"train_number":"19409","train_name":"GORAKHPUR EXP"},
{"train_number":"15046","train_name":"GORAKHPUR EXP"},
{"train_number":"12592","train_name":"GORAKHPUR EXP"},
{"train_number":"15017","train_name":"GORAKHPUR EXP"},
{"train_number":"12590","train_name":"GORAKHPUR EXP"},
{"train_number":"13154","train_name":"GOUR EXP"},
{"train_number":"23154","train_name":"GOUR EXP"},
{"train_number":"13153","train_name":"GOUR EXPRESS"},
{"train_number":"12738","train_name":"GOUTAMI EXP"},
{"train_number":"12737","train_name":"GOUTAMI EXP"},
{"train_number":"01221","train_name":""},
{"train_number":"12615","train_name":"GRAND TRUNK EXP"},
{"train_number":"23111","train_name":""},
{"train_number":"23112","train_name":""},
{"train_number":"53520","train_name":"GRD LINK PAS EX"},
{"train_number":"57478","train_name":"GTL TPTY PASSENGER"},
{"train_number":"","train_name":""},
{"train_number":"19012","train_name":"GUJARAT EXPRESS"},
{"train_number":"12901","train_name":"GUJARAT MAIL"},
{"train_number":"12902","train_name":"GUJARAT MAIL"},
{"train_number":"19033","train_name":"GUJARAT QUEEN"},
{"train_number":"19109","train_name":""},
{"train_number":"19034","train_name":"GUJARAT QUEEN"},
{"train_number":"19110","train_name":""},
{"train_number":"12917","train_name":"GUJARAT SMPRK K"},
{"train_number":"12918","train_name":"GUJRAT S KRANTI"},
{"train_number":"12659","train_name":"GURUDEV EXPRESS"},
{"train_number":"12660","train_name":"GURUDEV EXPRESS"},
{"train_number":"16342","train_name":"GURUVAYUR EXP"},
{"train_number":"16128","train_name":"GUV CHENNAI EXP"},
{"train_number":"12507","train_name":"GUWAHATI EXP"},
{"train_number":"12515","train_name":"GUWAHATI EXP"},
{"train_number":"12509","train_name":"GUWAHATI EXP"},
{"train_number":"06336","train_name":"HOLIDAY SPL"},
{"train_number":"15645","train_name":"GUWAHATI EXPRES"},
{"train_number":"15647","train_name":"GUWAHATI EXPRES"},
{"train_number":"15629","train_name":"GUWAHATI EXPRES"},
{"train_number":"15635","train_name":"GUWAHATI EXPRES"},
{"train_number":"15630","train_name":"GUWAHATI MS EXP"},
{"train_number":"11124","train_name":"GWL BJU MAIL"},
{"train_number":"11126","train_name":"GWL INDB EXPRES"},
{"train_number":"12197","train_name":"GWL INTERCITY"},
{"train_number":"01016","train_name":""},
{"train_number":"11102","train_name":"GWL PUNE EXP"},
{"train_number":"11112","train_name":"GWL SUSHASAN EX"},
{"train_number":"22131","train_name":"GYAN GANGA EXP"},
{"train_number":"22132","train_name":"GYAN GANGA SF"},
{"train_number":"12153","train_name":"HABIBGANJ EXP"},
{"train_number":"22613","train_name":"HALDIA EXPRESS"},
{"train_number":"12755","train_name":""},
{"train_number":"59812","train_name":"JAB RTM PASSENGER"},
{"train_number":"59811","train_name":"RTM AF PASSENGER"},
{"train_number":"16592","train_name":"HAMPI EXP"},
{"train_number":"16591","train_name":"HAMPI EXPRESS"},
{"train_number":"22939","train_name":"HAPA BSP EXPRES"},
{"train_number":"09535","train_name":""},
{"train_number":"12997","train_name":""},
{"train_number":"19577","train_name":"HAPA EXPRESS"},
{"train_number":"29059","train_name":"HAPA INTERCITY"},
{"train_number":"12475","train_name":"HAPA SVDK EXP"},
{"train_number":"22908","train_name":"HAPA MADGAON EX"},
{"train_number":"19578","train_name":"HAPA TEN EXPRES"},
{"train_number":"12998","train_name":""},
{"train_number":"22917","train_name":"HARIDWAR EXP"},
{"train_number":"19031","train_name":"HARIDWAR MAIL"},
{"train_number":"19105","train_name":""},
{"train_number":"14523","train_name":"HARIHARNATH EXP"},
{"train_number":"17416","train_name":"HARIPRIYA EXP"},
{"train_number":"17415","train_name":"HARIPRIYA EXP"},
{"train_number":"13163","train_name":"HATE BAZARE EXP"},
{"train_number":"13164","train_name":"HATE BAZARE EXP"},
{"train_number":"12811","train_name":"HATIA EXPRESS"},
{"train_number":"13113","train_name":"HAZARDUARI EXP"},
{"train_number":"13114","train_name":"HAZARDUARI EXP"},
{"train_number":"01653","train_name":""},
{"train_number":"59394","train_name":"HBJ DHD PASSENGER"},
{"train_number":"22184","train_name":"HBJ DOUBLE DECK"},
{"train_number":"01659","train_name":""},
{"train_number":"12062","train_name":"HBJ JANSHATABDI"},
{"train_number":"01267","train_name":""},
{"train_number":"12154","train_name":"HBJ LTT SUP EXP"},
{"train_number":"01658","train_name":""},
{"train_number":"01652","train_name":""},
{"train_number":"02185","train_name":""},
{"train_number":"02189","train_name":""},
{"train_number":"02191","train_name":""},
{"train_number":"12364","train_name":"HDB KOAA SF EXP"},
{"train_number":"14610","train_name":"HEMKUNT EXP"},
{"train_number":"14609","train_name":"HEMKUNT EXP"},
{"train_number":"05698","train_name":""},
{"train_number":"05697","train_name":""},
{"train_number":"14553","train_name":"HIMACHAL EXP"},
{"train_number":"14554","train_name":"HIMACHAL EXPRES"},
{"train_number":"14096","train_name":"HIMALAYAN QUEEN"},
{"train_number":"52456","train_name":"HIMALYAN  QUEEN"},
{"train_number":"14095","train_name":"HIMALYAN QUEEN"},
{"train_number":"52455","train_name":"HIMALYAN QUEEN"},
{"train_number":"12332","train_name":"HIMGIRI EXPRESS"},
{"train_number":"12331","train_name":"HIMGIRI EXPRESS"},
{"train_number":"16317","train_name":"HIMSAGAR EXP"},
{"train_number":"16318","train_name":"HIMSAGAR EXP"},
{"train_number":"18448","train_name":"HIRAKHAND EXP"},
{"train_number":"18447","train_name":"HIRAKHAND EXP"},
{"train_number":"18508","train_name":"HIRAKUND EXP"},
{"train_number":"02443","train_name":""},
{"train_number":"12443","train_name":"HLZ ANVT WKLY S"},
{"train_number":"22614","train_name":"HLZ MAS SUP EXP"},
{"train_number":"12756","train_name":""},
{"train_number":"22982","train_name":"SGNR KOTA SF"},
{"train_number":"09733","train_name":""},
{"train_number":"04751","train_name":""},
{"train_number":"13051","train_name":"HOOL EXPRESS"},
{"train_number":"13052","train_name":"HOOL EXPRESS"},
{"train_number":"56909","train_name":"SBC HPT PASSENGER"},
{"train_number":"12221","train_name":"HOWRAH DURONTO"},
{"train_number":"12261","train_name":"HOWRAH DURONTO"},
{"train_number":"12572","train_name":""},
{"train_number":"22832","train_name":"HOWRAH EXP"},
{"train_number":"12833","train_name":"HOWRAH EXPRESS"},
{"train_number":"12664","train_name":"HOWRAH EXPRESS"},
{"train_number":"12809","train_name":"HOWRAH MAIL"},
{"train_number":"12840","train_name":"HOWRAH MAIL"},
{"train_number":"12869","train_name":"HOWRAH SUP EXP"},
{"train_number":"54601","train_name":"HSR ASR PASSENGER"},
{"train_number":"02916","train_name":""},
{"train_number":"22916","train_name":"HSR BDTS S F EX"},
{"train_number":"54834","train_name":"HSR JP PASSENGER"},
{"train_number":"14012","train_name":"HSX DLI EXP"},
{"train_number":"04414","train_name":"NDLS LKO AC SPL"},
{"train_number":"02084","train_name":""},
{"train_number":"01088","train_name":""},
{"train_number":"08894","train_name":""},
{"train_number":"12812","train_name":"HTE LTT SUPER"},
{"train_number":"08612","train_name":""},
{"train_number":"18626","train_name":"HTE PNBE EXP"},
{"train_number":"22846","train_name":"HTE PUNE EXP"},
{"train_number":"18624","train_name":"HTE RJPB EXP"},
{"train_number":"18616","train_name":"KRIYA YOGA EXP"},
{"train_number":"08047","train_name":""},
{"train_number":"18637","train_name":"HTE BNC EXP"},
{"train_number":"12835","train_name":"HTE YPR EXPRESS"},
{"train_number":"08635","train_name":""},
{"train_number":"08637","train_name":""},
{"train_number":"02686","train_name":""},
{"train_number":"12778","train_name":"HUBLI EXP"},
{"train_number":"06567","train_name":""},
{"train_number":"01494","train_name":""},
{"train_number":"56501","train_name":"BZA UBL PASSENGER"},
{"train_number":"17224","train_name":""},
{"train_number":"17223","train_name":""},
{"train_number":"12701","train_name":"HUSAINSAGAR EXP"},
{"train_number":"12702","train_name":"HUSSAINSAGAR EX"},
{"train_number":"12158","train_name":"HUTATMA EXPRESS"},
{"train_number":"12157","train_name":"HUTATMA EXPRESS"},
{"train_number":"19106","train_name":""},
{"train_number":"19032","train_name":"YOGA EXPRESS"},
{"train_number":"19610","train_name":"HW AII EXP"},
{"train_number":"09639","train_name":""},
{"train_number":"14116","train_name":"HW ALD EXP"},
{"train_number":"12053","train_name":"HW ASR JNSHTBDI"},
{"train_number":"22918","train_name":"HW BDTS SF EXP"},
{"train_number":"04736","train_name":""},
{"train_number":"12912","train_name":"HW BL SUP EXP"},
{"train_number":"24887","train_name":"HW BME LINK EXP"},
{"train_number":"04058","train_name":""},
{"train_number":"12370","train_name":"HW HWH S F EXP"},
{"train_number":"03016","train_name":""},
{"train_number":"03116","train_name":""},
{"train_number":"12172","train_name":"HW LTT AC SF"},
{"train_number":"04316","train_name":""},
{"train_number":"03015","train_name":""},
{"train_number":"15033","train_name":"HW RMR EXP"},
{"train_number":"12063","train_name":"HW UHL LINK JSH"},
{"train_number":"12834","train_name":"HWH ADI EXPRESS"},
{"train_number":"03001","train_name":""},
{"train_number":"58013","train_name":"HWH BKSC PASSENGER"},
{"train_number":"13063","train_name":"HWH BLGT EXP"},
{"train_number":"13025","train_name":"HWH BPL EXPRESS"},
{"train_number":"58011","train_name":"HWH CKP PASSENGER"},
{"train_number":"12262","train_name":"HWH CSTM DURONT"},
{"train_number":"12870","train_name":"HWH CSTM EXPRES"},
{"train_number":"02042","train_name":""},
{"train_number":"15235","train_name":"HWH DBG EXPRESS"},
{"train_number":"53041","train_name":"HWH JYG PASSENGER"},
{"train_number":"12847","train_name":"DGHA SUP AC EXP"},
{"train_number":"02249","train_name":""},
{"train_number":"12385","train_name":""},
{"train_number":"12311","train_name":"HWH DLI KLK MAI"},
{"train_number":"12274","train_name":"HWH DURONTO EXP"},
{"train_number":"13023","train_name":"HWH GAYA EXPRES"},
{"train_number":"25639","train_name":""},
{"train_number":"03057","train_name":""},
{"train_number":"05639","train_name":""},
{"train_number":"02501","train_name":""},
{"train_number":"03067","train_name":""},
{"train_number":"18615","train_name":"KRIYA YOGA EXP"},
{"train_number":"03003","train_name":""},
{"train_number":"13071","train_name":"HWH JMP EXPRESS"},
{"train_number":"12371","train_name":"HWH JSM EXP"},
{"train_number":"12307","train_name":"HWH JU  EXPRESS"},
{"train_number":"04824","train_name":""},
{"train_number":"13016","train_name":""},
{"train_number":"15711","train_name":"HWH KIR EXPRESS"},
{"train_number":"18005","train_name":"HWH KORAPUT EXP"},
{"train_number":"12353","train_name":"HWH LKU EXP"},
{"train_number":"02242","train_name":""},
{"train_number":"03061","train_name":""},
{"train_number":"02870","train_name":""},
{"train_number":"12839","train_name":"HWH MAS MAIL"},
{"train_number":"02841","train_name":""},
{"train_number":"53049","train_name":"HWH MKA PASSENGER"},
{"train_number":"53003","train_name":"HWH MLDT PASSENGER"},
{"train_number":"13011","train_name":"HWH MLDT INT EX"},
{"train_number":"03465","train_name":""},
{"train_number":"12321","train_name":"HWH MUMBAI MAIL"},
{"train_number":"12810","train_name":"HWH MUMBAI MAIL"},
{"train_number":"22817","train_name":"HWH MYS EXPRESS"},
{"train_number":"12323","train_name":"HWH ANVT EXPRES"},
{"train_number":"12249","train_name":"HWH ANVT YUVA E"},
{"train_number":"22309","train_name":"HWH NJP AC EXP"},
{"train_number":"03063","train_name":""},
{"train_number":"05709","train_name":""},
{"train_number":"12906","train_name":"HWH PBR  OKHAEX"},
{"train_number":"12867","train_name":"HWH PDY EXP"},
{"train_number":"03073","train_name":""},
{"train_number":"03065","train_name":""},
{"train_number":"03071","train_name":""},
{"train_number":"02241","train_name":""},
{"train_number":"12827","train_name":"HWH PRR EXP"},
{"train_number":"12222","train_name":"HWH PUNE DURONT"},
{"train_number":"12837","train_name":"HWH PURI EXP"},
{"train_number":"12887","train_name":"HWH PURI EXPRES"},
{"train_number":"12895","train_name":"HWH PURI EXPRES"},
{"train_number":"12881","train_name":""},
{"train_number":"18617","train_name":""},
{"train_number":"18627","train_name":"HWH RNC INT EXP"},
{"train_number":"22891","train_name":"HWH RNC INT EXP"},
{"train_number":"13043","train_name":"HWH RXL EXPRESS"},
{"train_number":"03043","train_name":""},
{"train_number":"03029","train_name":""},
{"train_number":"03543","train_name":""},
{"train_number":"22803","train_name":"HWH SBP SUP EXP"},
{"train_number":"12585","train_name":""},
{"train_number":"12574","train_name":""},
{"train_number":"22894","train_name":"HWH SNSI EXPRES"},
{"train_number":"12571","train_name":""},
{"train_number":"22831","train_name":"HWH SSPN EXPRES"},
{"train_number":"13053","train_name":"HWH SURI EXP"},
{"train_number":"12663","train_name":"HWH TPJ EXPRESS"},
{"train_number":"22863","train_name":"HWH YPR AC EXP"},
{"train_number":"12245","train_name":"HWH YPR DURONTO"},
{"train_number":"12863","train_name":"HWH YPR EXPRESS"},
{"train_number":"02863","train_name":""},
{"train_number":"07091","train_name":""},
{"train_number":"08564","train_name":""},
{"train_number":"07028","train_name":""},
{"train_number":"17020","train_name":"HYB AII  EXP"},
{"train_number":"07020","train_name":""},
{"train_number":"12720","train_name":"HYB AII SUP EXP"},
{"train_number":"17010","train_name":""},
{"train_number":"57130","train_name":"HYB BJP PASSENGER"},
{"train_number":"17011","train_name":""},
{"train_number":"07011","train_name":"HOLIDAY SPL"},
{"train_number":"07001","train_name":""},
{"train_number":"07137","train_name":""},
{"train_number":"07021","train_name":""},
{"train_number":"07125","train_name":""},
{"train_number":"11303","train_name":"HYB KOP EXPRESS"},
{"train_number":"17003","train_name":""},
{"train_number":"07143","train_name":""},
{"train_number":"01032","train_name":""},
{"train_number":"07003","train_name":""},
{"train_number":"06306","train_name":""},
{"train_number":"57563","train_name":"HYB PBN PASSENGER"},
{"train_number":"17014","train_name":"HYB PUNE EXP"},
{"train_number":"07107","train_name":""},
{"train_number":"07115","train_name":"HOLIDAY SPL"},
{"train_number":"07109","train_name":""},
{"train_number":"07105","train_name":""},
{"train_number":"07166","train_name":""},
{"train_number":"07429","train_name":""},
{"train_number":"17005","train_name":"HYB RXL EXPRESS"},
{"train_number":"07128","train_name":""},
{"train_number":"17031","train_name":"HYDERABAD EXP"},
{"train_number":"07165","train_name":""},
{"train_number":"12603","train_name":"HYDERABAD EXP"},
{"train_number":"07110","train_name":""},
{"train_number":"07106","train_name":""},
{"train_number":"07108","train_name":""},
{"train_number":"57550","train_name":"AWB HYB PASSENGER"},
{"train_number":"22941","train_name":"INBD JAT S F EX"},
{"train_number":"19325","train_name":"IND AMRITSAR EX"},
{"train_number":"14317","train_name":"IND DDN EXPRESS"},
{"train_number":"22183","train_name":"IND DOUBLE DECK"},
{"train_number":"","train_name":""},
{"train_number":"11125","train_name":"IND GWALIAR EXP"},
{"train_number":"22944","train_name":"IND PUNE EXPRES"},
{"train_number":"19312","train_name":"IND PUNE EXPRES"},
{"train_number":"59307","train_name":""},
{"train_number":"09311","train_name":""},
{"train_number":"14319","train_name":"INDB BARELLY EX"},
{"train_number":"09302","train_name":""},
{"train_number":"11701","train_name":"INDB INTERCITY"},
{"train_number":"19324","train_name":"INDB INTERCITY"},
{"train_number":"19801","train_name":"INDB INTERCITY"},
{"train_number":"39801","train_name":""},
{"train_number":"09307","train_name":""},
{"train_number":"11471","train_name":"INDB JBP EXP"},
{"train_number":"09728","train_name":""},
{"train_number":"12923","train_name":"INDB NAGPUR EXP"},
{"train_number":"19313","train_name":"INDB RJPB  EXP"},
{"train_number":"09305","train_name":""},
{"train_number":"19321","train_name":"INDB RJPB EXP"},
{"train_number":"09309","train_name":"INDORE SUVIDHA"},
{"train_number":"21125","train_name":"INDORE BHIND EX"},
{"train_number":"12227","train_name":"INDORE DURONTO"},
{"train_number":"19314","train_name":"INDORE EXPRESS"},
{"train_number":"19310","train_name":"INDORE GNC EXP"},
{"train_number":"22106","train_name":"INDRAYANI EXP"},
{"train_number":"22105","train_name":"INDRAYANI EXP"},
{"train_number":"18411","train_name":"INTER CITY EXP"},
{"train_number":"15603","train_name":"INTER CITY EXP"},
{"train_number":"18412","train_name":"INTER CITY EXP"},
{"train_number":"15720","train_name":"INTERCITY"},
{"train_number":"15719","train_name":"INTERCITY"},
{"train_number":"13401","train_name":"INTERCITY   EXP"},
{"train_number":"15604","train_name":"INTERCITY  EXP"},
{"train_number":"12383","train_name":"INTERCITY  EXP"},
{"train_number":"12384","train_name":"INTERCITY  EXP"},
{"train_number":"13402","train_name":"INTERCITY  EXP"},
{"train_number":"12416","train_name":"INTERCITY  EXP"},
{"train_number":"14211","train_name":"INTERCITY EXP"},
{"train_number":"15616","train_name":""},
{"train_number":"12466","train_name":"INTERCITY EXP"},
{"train_number":"13236","train_name":"INTERCITY EXP"},
{"train_number":"19802","train_name":"INTERCITY EXP"},
{"train_number":"15615","train_name":""},
{"train_number":"19412","train_name":"INTERCITY EXP"},
{"train_number":"13465","train_name":"INTERCITY EXP"},
{"train_number":"13466","train_name":"INTERCITY EXP"},
{"train_number":"12127","train_name":"INTERCITY EXP"},
{"train_number":"12412","train_name":"INTERCITY EXP"},
{"train_number":"22609","train_name":"INTERCITY EXP"},
{"train_number":"12411","train_name":"INTERCITY EXP"},
{"train_number":"22610","train_name":"INTERCITY EXP"},
{"train_number":"14316","train_name":"INTERCITY EXP"},
{"train_number":"14315","train_name":"INTERCITY EXP"},
{"train_number":"12726","train_name":"INTERCITY EXP"},
{"train_number":"12725","train_name":"INTERCITY EXP"},
{"train_number":"13235","train_name":"INTERCITY EXP"},
{"train_number":"15470","train_name":""},
{"train_number":"15471","train_name":""},
{"train_number":"11451","train_name":"INTERCITY EXP"},
{"train_number":"15472","train_name":""},
{"train_number":"14212","train_name":"INTERCITY EXP"},
{"train_number":"12481","train_name":"INTERCITY EXP"},
{"train_number":"13503","train_name":""},
{"train_number":"19323","train_name":"INTERCITY EXP"},
{"train_number":"13504","train_name":""},
{"train_number":"12128","train_name":"INTERCITY EXP"},
{"train_number":"15469","train_name":""},
{"train_number":"12482","train_name":"INTERCITY EXP"},
{"train_number":"15714","train_name":"INTERCITY EXP"},
{"train_number":"15713","train_name":"INTERCITY EXP"},
{"train_number":"11452","train_name":"INTERCITY EXP"},
{"train_number":"13225","train_name":"INTERCITY EXPRE"},
{"train_number":"22188","train_name":"INTERCITY EXPRE"},
{"train_number":"12530","train_name":"LJN PPTA SF EXP"},
{"train_number":"13226","train_name":"INTERCITY EXPRE"},
{"train_number":"12529","train_name":"PPTA LJN SF EXP"},
{"train_number":"22187","train_name":"INTERCITY EXPRE"},
{"train_number":"18695","train_name":"IPR RJPB EXPRES"},
{"train_number":"13251","train_name":""},
{"train_number":"12872","train_name":"ISPAT EXPRESS"},
{"train_number":"12871","train_name":"ISPAT EXPRESS"},
{"train_number":"58112","train_name":"ITR TATA PASSENGER"},
{"train_number":"01705","train_name":"HOLIDAY SPL"},
{"train_number":"19771","train_name":""},
{"train_number":"12239","train_name":"JAIPUR DURONTO"},
{"train_number":"12967","train_name":"JAIPUR EXP"},
{"train_number":"19573","train_name":"JAIPUR EXPRESS"},
{"train_number":"12973","train_name":"JAIPUR EXPRESS"},
{"train_number":"12975","train_name":"JAIPUR EXPRESS"},
{"train_number":"54805","train_name":"ADI JP PASSENGER"},
{"train_number":"09043","train_name":""},
{"train_number":"09025","train_name":""},
{"train_number":"09047","train_name":""},
{"train_number":"12979","train_name":"JAIPUR SUP FAST"},
{"train_number":"18104","train_name":"JALIANWALA B EX"},
{"train_number":"12380","train_name":"JALIANWALA B EX"},
{"train_number":"18103","train_name":"JALIANWALA B EX"},
{"train_number":"12379","train_name":"JALIANWALAB EXP"},
{"train_number":"12477","train_name":"JAM SVDK EXP"},
{"train_number":"12414","train_name":"JAMMU AII EXP"},
{"train_number":"12207","train_name":"JAMMU GARIB RAT"},
{"train_number":"15654","train_name":"JAMMU GHY EXPRE"},
{"train_number":"12588","train_name":"JAMMU GKP EXP"},
{"train_number":"14033","train_name":"JAMMU MAIL"},
{"train_number":"24033","train_name":""},
{"train_number":"24034","train_name":""},
{"train_number":"14034","train_name":"JAMMU MAIL"},
{"train_number":"12426","train_name":"JAMMU RAJDHANI"},
{"train_number":"12425","train_name":"JAMMU RAJDHANI"},
{"train_number":"13151","train_name":"JAMMU TAWI EXP"},
{"train_number":"11449","train_name":"JBP SVDK EXP"},
{"train_number":"19059","train_name":"JAMNAGAR INTCIT"},
{"train_number":"12082","train_name":"JAN SHATABDI"},
{"train_number":"12075","train_name":"JAN SHATABDI"},
{"train_number":"12081","train_name":"JAN SHATABDI"},
{"train_number":"12078","train_name":"JAN SHATABDI"},
{"train_number":"12077","train_name":"JAN SHATABDI"},
{"train_number":"12076","train_name":"JAN SHATABDI"},
{"train_number":"12071","train_name":"JAN SHATABDI EX"},
{"train_number":"12080","train_name":"JAN SHATABDI EX"},
{"train_number":"12084","train_name":"JAN SHATABDI EX"},
{"train_number":"12052","train_name":"JAN SHATABDI EX"},
{"train_number":"12051","train_name":"JAN SHATABDI EX"},
{"train_number":"12067","train_name":"JAN SHATABDI EX"},
{"train_number":"12068","train_name":"JAN SHATABDI EX"},
{"train_number":"12083","train_name":"JAN SHATABDI EX"},
{"train_number":"13419","train_name":"JANASEWA EXPRES"},
{"train_number":"13205","train_name":""},
{"train_number":"13206","train_name":""},
{"train_number":"19107","train_name":"JANMABHOOMI  EX"},
{"train_number":"19108","train_name":"JANMABHOOMI EXP"},
{"train_number":"12806","train_name":"JANMABHOOMI EXP"},
{"train_number":"12805","train_name":"JANMABHOOMI EXP"},
{"train_number":"13420","train_name":"JANSEWA EXPRESS"},
{"train_number":"12079","train_name":"JANSHATABDI EXP"},
{"train_number":"12023","train_name":"JANSHATABDI EXP"},
{"train_number":"12072","train_name":"JANSHATABDI EXP"},
{"train_number":"12069","train_name":"JANSHATABDI EXP"},
{"train_number":"12024","train_name":"JANSHATABDI EXP"},
{"train_number":"12070","train_name":"JANSHATABDI EXP"},
{"train_number":"13039","train_name":""},
{"train_number":"11450","train_name":"SVDK JBP EXP"},
{"train_number":"19224","train_name":"JAT ADI EXPRESS"},
{"train_number":"02208","train_name":""},
{"train_number":"04122","train_name":""},
{"train_number":"04132","train_name":""},
{"train_number":"","train_name":""},
{"train_number":"19226","train_name":"JAT BTI EXP"},
{"train_number":"12470","train_name":"JAT CNB EXPRESS"},
{"train_number":"02452","train_name":""},
{"train_number":"05144","train_name":""},
{"train_number":"02172","train_name":"JAT CSTM SUIVDH"},
{"train_number":"04038","train_name":""},
{"train_number":"18216","train_name":"JAT DURG EXP"},
{"train_number":"12550","train_name":"JAT DURG SF EXP"},
{"train_number":"02530","train_name":""},
{"train_number":"05044","train_name":""},
{"train_number":"12476","train_name":"SVDK HAPA EXP"},
{"train_number":"03004","train_name":""},
{"train_number":"07022","train_name":""},
{"train_number":"22942","train_name":"JAT INDB SF EXP"},
{"train_number":"09308","train_name":""},
{"train_number":"12478","train_name":"SVDK JAM EXP"},
{"train_number":"19804","train_name":"SVDK KOTA EXP"},
{"train_number":"18110","train_name":"JAT MURI ROU EX"},
{"train_number":"02422","train_name":""},
{"train_number":"02445","train_name":""},
{"train_number":"14714","train_name":"JAT SGNR EXP"},
{"train_number":"04734","train_name":""},
{"train_number":"05720","train_name":""},
{"train_number":"13160","train_name":"JBN KOLKATA EXP"},
{"train_number":"22181","train_name":"JBP  NZM EXPRES"},
{"train_number":"12160","train_name":"JBP AMI SUP EXP"},
{"train_number":"01753","train_name":""},
{"train_number":"01755","train_name":""},
{"train_number":"58870","train_name":""},
{"train_number":"58868","train_name":""},
{"train_number":"01731","train_name":""},
{"train_number":"01702","train_name":""},
{"train_number":"01707","train_name":"HOLIDAY SPL"},
{"train_number":"12188","train_name":"JBP GARIB RATH"},
{"train_number":"02188","train_name":""},
{"train_number":"01709","train_name":""},
