[
{"train_number":"12723","train_name":"TELANGANA  EXP"},
{"train_number":"22416","train_name":"A P EXP"},
{"train_number":"12724","train_name":"TELANGANA EXP"},
{"train_number":"12707","train_name":"A P SMPRK KRNTI"},
{"train_number":"15909","train_name":"ABADH ASSAM EXP"},
{"train_number":"15609","train_name":""},
{"train_number":"18242","train_name":""},
{"train_number":"11266","train_name":"ABKP JBP EXPRES"},
{"train_number":"58702","train_name":"ABKP SDL PASSENGER"},
{"train_number":"54703","train_name":"ABS JU PASSENGER"},
{"train_number":"07509","train_name":""},
{"train_number":"09416","train_name":""},
{"train_number":"09427","train_name":""},
{"train_number":"09018","train_name":""},
{"train_number":"14804","train_name":"ADI BGKT EXPRES"},
{"train_number":"04804","train_name":""},
{"train_number":"09421","train_name":""},
{"train_number":"19130","train_name":""},
{"train_number":"02713","train_name":""},
{"train_number":"19420","train_name":"ADI CHENNAI EXP"},
{"train_number":"09417","train_name":""},
{"train_number":"12931","train_name":"ADI DOUBLE DECK"},
{"train_number":"12267","train_name":"ADI DURONTO EXP"},
{"train_number":"12298","train_name":"ADI DURONTO EXP"},
{"train_number":"09425","train_name":""},
{"train_number":"19223","train_name":"ADI JAT EXPRESS"},
{"train_number":"02207","train_name":""},
{"train_number":"19606","train_name":""},
{"train_number":"09407","train_name":""},
{"train_number":"09413","train_name":""},
{"train_number":"09420","train_name":""},
{"train_number":"09411","train_name":""},
{"train_number":"09409","train_name":""},
{"train_number":"12844","train_name":"ADI PURI EXP"},
{"train_number":"18406","train_name":"ADI PURI EXP"},
{"train_number":"07017","train_name":""},
{"train_number":"12958","train_name":"ADI SJ RAJDHANI"},
{"train_number":"19415","train_name":"ADI SVDK EXPRES"},
{"train_number":"19944","train_name":"ADI UDZ EXPRESS"},
{"train_number":"19407","train_name":"ADI VARANASI EX"},
{"train_number":"16501","train_name":"ADI YPR EXPRESS"},
{"train_number":"12547","train_name":"AF ADI SF EXP"},
{"train_number":"12195","train_name":"AF AII INTERCIT"},
{"train_number":"09612","train_name":""},
{"train_number":"12036","train_name":"AF JP SHATABDI"},
{"train_number":"15055","train_name":"AF RMR EXPRESS"},
{"train_number":"12954","train_name":"AG KRANTI RJDHN"},
{"train_number":"12320","train_name":"AGC KOAA EXP"},
{"train_number":"13168","train_name":"AGC KOAA EXP"},
{"train_number":"01436","train_name":""},
{"train_number":"12342","train_name":"AGNIBINA EXPRES"},
{"train_number":"12341","train_name":"AGNIBINA EXPRES"},
{"train_number":"12548","train_name":"AGRA SUPER FAST"},
{"train_number":"52575","train_name":"JOYRIDE DIESEL"},
{"train_number":"15696","train_name":""},
{"train_number":"22646","train_name":"AHILYANAGARI EX"},
{"train_number":"22645","train_name":"AHILYANAGARI EX"},
{"train_number":"16326","train_name":""},
{"train_number":"11096","train_name":"AHIMSA EXPRESS"},
{"train_number":"11095","train_name":"AHIMSA EXPRESS"},
{"train_number":"16502","train_name":"AHMADABAD EXP"},
{"train_number":"59440","train_name":"ADI BCT PASSENGER"},
{"train_number":"59439","train_name":"BCT ADI PASSENGER"},
{"train_number":"19405","train_name":""},
{"train_number":"09419","train_name":""},
{"train_number":"11050","train_name":"AHMEDABAD EXP"},
{"train_number":"59441","train_name":"BCT ADI PASSENGER"},
{"train_number":"59442","train_name":"ADI BCT PASSENGER"},
{"train_number":"09649","train_name":""},
{"train_number":"12196","train_name":"AII AF INTERCIT"},
{"train_number":"05712","train_name":""},
{"train_number":"22996","train_name":"AII BDTS SF EXP"},
{"train_number":"09611","train_name":""},
{"train_number":"09619","train_name":""},
{"train_number":"09602","train_name":"HOLIDAY SPL"},
{"train_number":"09601","train_name":""},
{"train_number":"13424","train_name":"AII BGP EXP"},
{"train_number":"05286","train_name":""},
{"train_number":"12983","train_name":"AII CDG G RATH"},
{"train_number":"05104","train_name":""},
{"train_number":"05238","train_name":""},
{"train_number":"12990","train_name":"AII DDR  EXPRES"},
{"train_number":"09627","train_name":"HOLIDAY SPL"},
{"train_number":"04042","train_name":""},
{"train_number":"18208","train_name":"AII DURG EXP"},
{"train_number":"19609","train_name":"AII HW EXP"},
{"train_number":"09640","train_name":""},
{"train_number":"03002","train_name":""},
{"train_number":"17019","train_name":"AII HYB EXP"},
{"train_number":"12719","train_name":"AII HYB SF EXP"},
{"train_number":"07019","train_name":""},
{"train_number":"07126","train_name":""},
{"train_number":"09312","train_name":""},
{"train_number":"12066","train_name":"AII JAN SHATABD"},
{"train_number":"12413","train_name":"AII JAT EXPRESS"},
{"train_number":"09720","train_name":""},
{"train_number":"09621","train_name":""},
{"train_number":"09625","train_name":"UDZ AWR SF SPL"},
{"train_number":"54802","train_name":"AII JU PASSENGER"},
{"train_number":"09615","train_name":""},
{"train_number":"07130","train_name":""},
{"train_number":"03138","train_name":""},
{"train_number":"19608","train_name":"AII KOAA EXP"},
{"train_number":"16209","train_name":"AII MYS EXPRESS"},
{"train_number":"22211","train_name":""},
{"train_number":"08422","train_name":""},
{"train_number":"18422","train_name":"AII PURI EXP"},
{"train_number":"19654","train_name":"AII RTM EXP"},
{"train_number":"12988","train_name":"AII SDAH EXPRES"},
{"train_number":"03180","train_name":""},
{"train_number":"19603","train_name":""},
{"train_number":"09609","train_name":""},
{"train_number":"19607","train_name":"AII WKLY EXP"},
{"train_number":"17063","train_name":"AJANTA EXPRESS"},
{"train_number":"17064","train_name":"AJANTA EXPRESS"},
{"train_number":"19611","train_name":"AJMER ASR EXP"},
{"train_number":"19613","train_name":"AJMER ASR EXP"},
{"train_number":"12989","train_name":"AJMER EXPRESS"},
{"train_number":"16210","train_name":"AJMER EXPRESS"},
{"train_number":"19411","train_name":"AJMER INTERCITY"},
{"train_number":"12016","train_name":"AJMER SHTBDI"},
{"train_number":"12015","train_name":"AJMER SHTBDI"},
{"train_number":"09650","train_name":""},
{"train_number":"12120","train_name":""},
{"train_number":"11202","train_name":"AJNI LTT EXPRES"},
{"train_number":"17640","train_name":"AK KCG EXP"},
{"train_number":"52994","train_name":"AK MHOW PASSENGER"},
{"train_number":"07507","train_name":""},
{"train_number":"12318","train_name":"AKAL TAKHAT EXP"},
{"train_number":"12317","train_name":"AKAL TAKHT EXP"},
{"train_number":"14312","train_name":"ALA HAZRAT EXP"},
{"train_number":"14311","train_name":"ALA HAZRAT EXP"},
{"train_number":"07092","train_name":""},
{"train_number":"09430","train_name":""},
{"train_number":"09428","train_name":""},
{"train_number":"04421","train_name":"KGM NDLS SPL"},
{"train_number":"04117","train_name":""},
{"train_number":"07240","train_name":""},
{"train_number":"04001","train_name":""},
{"train_number":"12276","train_name":"ALD DURONTO EXP"},
{"train_number":"12293","train_name":"ALD DURONTO EXP"},
{"train_number":"14115","train_name":"ALD HW EXP"},
{"train_number":"04120","train_name":""},
{"train_number":"09314","train_name":""},
{"train_number":"22442","train_name":""},
{"train_number":"04121","train_name":""},
{"train_number":"04131","train_name":""},
{"train_number":"12403","train_name":"ALD JP EXPRESS"},
{"train_number":"12294","train_name":"ALD LTT DURONTO"},
{"train_number":"04127","train_name":""},
{"train_number":"12564","train_name":""},
{"train_number":"04115","train_name":""},
{"train_number":"01006","train_name":""},
{"train_number":"04111","train_name":""},
{"train_number":"04423","train_name":""},
{"train_number":"07512","train_name":""},
{"train_number":"07514","train_name":""},
{"train_number":"04124","train_name":""},
{"train_number":"09016","train_name":""},
{"train_number":"04113","train_name":""},
{"train_number":"08576","train_name":""},
{"train_number":"09429","train_name":""},
{"train_number":"09313","train_name":""},
{"train_number":"16308","train_name":"ALLEPPEY EXP"},
{"train_number":"22639","train_name":"ALLEPPEY EXP"},
{"train_number":"12587","train_name":"AMAR NATH EXP"},
{"train_number":"18047","train_name":"AMARAVATHI EXP"},
{"train_number":"17225","train_name":"AMARAVATHI EXP"},
{"train_number":"17226","train_name":"AMARAVATI EXP"},
{"train_number":"12854","train_name":"AMARKANTAK EXP"},
{"train_number":"12853","train_name":"AMARKANTAK EXP"},
{"train_number":"15097","train_name":"AMARNATH EXP"},
{"train_number":"15098","train_name":"AMARNATH EXP"},
{"train_number":"15653","train_name":"AMARNATH EXPRES"},
{"train_number":"11265","train_name":"AMBIKAPUR EXPRE"},
{"train_number":"13138","train_name":"AMH KOAA EXP"},
{"train_number":"11054","train_name":"AMH LTT EXP"},
{"train_number":"12119","train_name":""},
{"train_number":"12159","train_name":"AMI JBP SUP EXP"},
{"train_number":"11406","train_name":"AMI PUNE EXP"},
{"train_number":"12766","train_name":"AMI TPTY SUP EX"},
{"train_number":"09050","train_name":""},
{"train_number":"12112","train_name":"AMRAVATI CSTM E"},
{"train_number":"16343","train_name":"AMRITHA EXPRESS"},
{"train_number":"16344","train_name":"AMRITHA EXPRESS"},
{"train_number":"13049","train_name":"AMRITSAR EXP"},
{"train_number":"12483","train_name":"AMRITSAR EXP"},
{"train_number":"11057","train_name":"AMRITSAR EXPRES"},
{"train_number":"13005","train_name":"AMRITSAR MAIL"},
{"train_number":"12031","train_name":"AMRITSAR SHTBDI"},
{"train_number":"12032","train_name":"AMRITSAR SHTBDI"},
{"train_number":"12013","train_name":"AMRITSAR SHTBDI"},
{"train_number":"12014","train_name":"AMRITSAR SHTBDI"},
{"train_number":"22128","train_name":"ANANDWAN EXP"},
{"train_number":"22127","train_name":"ANANDWAN EXPRES"},
{"train_number":"16724","train_name":"ANANTAPURI EXP"},
{"train_number":"16723","train_name":"ANANTAPURI EXP"},
{"train_number":"12316","train_name":"ANANYA EXPRESS"},
{"train_number":"16032","train_name":"ANDAMAN EXPRESS"},
{"train_number":"16031","train_name":"ANDAMAN EXPRESS"},
{"train_number":"12254","train_name":"ANGA EXPRESS"},
{"train_number":"12253","train_name":"ANGA EXPRESS"},
{"train_number":"12315","train_name":"ANNANYA  EXPRES"},
{"train_number":"04422","train_name":"NDLS KGM SPL"},
{"train_number":"04118","train_name":"HOLIDAY SPL"},
{"train_number":"04028","train_name":""},
{"train_number":"03518","train_name":""},
{"train_number":"22406","train_name":"ANVT BGP G RATH"},
{"train_number":"14152","train_name":"ANVT CNB EXP"},
{"train_number":"05214","train_name":""},
{"train_number":"04053","train_name":""},
{"train_number":"12211","train_name":"ANVT GARIB RATH"},
{"train_number":"22409","train_name":"ANVT GARIB RATH"},
{"train_number":"02398","train_name":""},
{"train_number":"05038","train_name":""},
{"train_number":"05028","train_name":""},
{"train_number":"15058","train_name":"ANVT GKP EXP"},
{"train_number":"05036","train_name":""},
{"train_number":"05058","train_name":""},
{"train_number":"05052","train_name":""},
{"train_number":"05050","train_name":""},
{"train_number":"05040","train_name":""},
{"train_number":"12444","train_name":"ANVT HLZ S F EX"},
{"train_number":"12040","train_name":"NDLS KGM SHT"},
{"train_number":"13132","train_name":"ANVT KOAA EXP"},
{"train_number":"03126","train_name":""},
{"train_number":"15622","train_name":"ANVT KYQ EXPRES"},
{"train_number":"15026","train_name":"ANVT MAU EXP"},
{"train_number":"13430","train_name":"ANVT MLDT EXP"},
{"train_number":"03444","train_name":""},
{"train_number":"03210","train_name":""},
{"train_number":"02394","train_name":""},
{"train_number":"02365","train_name":""},
{"train_number":"02527","train_name":""},
{"train_number":"22488","train_name":""},
{"train_number":"12428","train_name":"ANVT REWA EXP"},
{"train_number":"03416","train_name":""},
{"train_number":"03190","train_name":""},
{"train_number":"22858","train_name":"ANVT SRC SF EXP"},
{"train_number":"08034","train_name":""},
{"train_number":"04403","train_name":""},
{"train_number":"04051","train_name":""},
{"train_number":"12708","train_name":"AP SMPRK KRANTI"},
{"train_number":"05711","train_name":""},
{"train_number":"05817","train_name":"HOLIDAY SPL"},
{"train_number":"05422","train_name":""},
{"train_number":"12885","train_name":"ARANYAK EXPRESS"},
{"train_number":"12886","train_name":"ARANYAK EXPRESS"},
{"train_number":"19707","train_name":"ARAVALI EXPRESS"},
{"train_number":"19708","train_name":"ARAVALI EXPRESS"},
{"train_number":"12356","train_name":"ARCHANA EXPRESS"},
{"train_number":"12355","train_name":"ARCHNA EXPRESS"},
{"train_number":"15814","train_name":""},
{"train_number":"15813","train_name":""},
{"train_number":"03560","train_name":""},
{"train_number":"12916","train_name":"ASHRAM EXPRESS"},
{"train_number":"12915","train_name":"ASHRAM EXPRESS"},
{"train_number":"03513","train_name":""},
{"train_number":"03517","train_name":""},
{"train_number":"12361","train_name":"ASN CSTM EXPRES"},
{"train_number":"13509","train_name":"ASN GD EXPRESS"},
{"train_number":"13507","train_name":"ASN GKP EXPRESS"},
{"train_number":"03563","train_name":""},
{"train_number":"12376","train_name":"ASN MAS EXPRESS"},
{"train_number":"03555","train_name":""},
{"train_number":"03511","train_name":""},
{"train_number":"03503","train_name":""},
{"train_number":"03557","train_name":""},
{"train_number":"03516","train_name":""},
{"train_number":"19614","train_name":"ASR AII EXP"},
{"train_number":"19612","train_name":"ASR AJMER EXP"},
{"train_number":"12242","train_name":"ASR CDG SUP"},
{"train_number":"14154","train_name":"ASR CNB EXPRESS"},
{"train_number":"15934","train_name":"ASR DBRG EXPRES"},
{"train_number":"14632","train_name":"ASR DDN EXPRESS"},
{"train_number":"54602","train_name":"ASR SDLP PASSENGER"},
{"train_number":"12054","train_name":"ASR HW JNSHTBDI"},
{"train_number":"13050","train_name":"ASR HWH EXPRESS"},
{"train_number":"13006","train_name":"ASR HWH MAIL"},
{"train_number":"19326","train_name":"ASR INDB EXPRES"},
{"train_number":"19772","train_name":""},
{"train_number":"19782","train_name":""},
{"train_number":"12484","train_name":"ASR KCVL EXPRES"},
{"train_number":"15708","train_name":"ASR KIR EXPRESS"},
{"train_number":"12358","train_name":"ASR KOAA SUP EX"},
{"train_number":"14616","train_name":"ASR LKU EXP"},
{"train_number":"11058","train_name":"ASR CSTM  EXP"},
{"train_number":"12460","train_name":"ASR NDLS EXP"},
{"train_number":"12716","train_name":"ASR NED EXPRESS"},
{"train_number":"12422","train_name":"ASR NED SF EXP"},
{"train_number":"14002","train_name":"ATTARI DLI EXP"},
{"train_number":"12953","train_name":"AUG KR RAJ EXP"},
{"train_number":"57549","train_name":"HYB AWB PASSENGER"},
{"train_number":"15910","train_name":"AVADH ASSAM EXP"},
{"train_number":"15610","train_name":""},
{"train_number":"19040","train_name":"AVADH EXPRESS"},
{"train_number":"19039","train_name":"AVADH EXPRESS"},
{"train_number":"19038","train_name":"AVADH EXPRESS"},
{"train_number":"19037","train_name":"AVADH EXPRESS"},
{"train_number":"12962","train_name":"AVANTIKA EXP"},
{"train_number":"12961","train_name":"AVANTIKA EXP"},
{"train_number":"17619","train_name":"AWB NED EXP"},
{"train_number":"07505","train_name":""},
{"train_number":"17621","train_name":"AWB RU EXPRESS"},
{"train_number":"07503","train_name":""},
{"train_number":"07405","train_name":""},
{"train_number":"14808","train_name":""},
{"train_number":"04805","train_name":"HOLIDAY SPL"},
{"train_number":"12129","train_name":"AZAD HIND EXP"},
{"train_number":"12130","train_name":"AZAD HIND EXP"},
{"train_number":"12948","train_name":"AZIMABAD EXPRES"},
{"train_number":"12947","train_name":"AZIMABAD EXPRES"},
{"train_number":"15665","train_name":"B  G  EXPRESS"},
{"train_number":"15666","train_name":"B G EXPRESS"},
{"train_number":"18450","train_name":"B NATH DHAM EXP"},
{"train_number":"18449","train_name":"B NATH DHAM EXP"},
{"train_number":"13019","train_name":"BAGH EXPRESS"},
{"train_number":"13020","train_name":"BAGH EXPRESS"},
{"train_number":"12577","train_name":"BAGMATI EXPRESS"},
{"train_number":"12578","train_name":"BAGMATI EXPRESS"},
{"train_number":"74639","train_name":""},
{"train_number":"19452","train_name":"BANDRA T EXP"},
{"train_number":"06347","train_name":""},
{"train_number":"16524","train_name":"BANGALORE EXP"},
{"train_number":"16316","train_name":"BANGALORE EXP"},
{"train_number":"16322","train_name":""},
{"train_number":"06314","train_name":""},
{"train_number":"06029","train_name":""},
{"train_number":"06572","train_name":""},
{"train_number":"12609","train_name":"BANGALORE EXP"},
{"train_number":"17236","train_name":"BANGALORE EXP"},
{"train_number":"16525","train_name":"BANGALORE EXP"},
{"train_number":"16538","train_name":""},
{"train_number":"12678","train_name":"BANGALORE EXP"},
{"train_number":"16228","train_name":"BANGALORE EXP"},
{"train_number":"16518","train_name":"BANGALORE EXP"},
{"train_number":"06590","train_name":""},
{"train_number":"12785","train_name":"BANGALORE EXP"},
{"train_number":"06516","train_name":""},
{"train_number":"12657","train_name":"BANGALORE MAIL"},
{"train_number":"56263","train_name":"MYS SBC PASSENGER"},
{"train_number":"12683","train_name":"BANGALORE SF EX"},
{"train_number":"22607","train_name":"BANGALORE SF EX"},
{"train_number":"06514","train_name":""},
{"train_number":"22694","train_name":"BANGLORE RAJDHN"},
{"train_number":"12494","train_name":""},
{"train_number":"22692","train_name":"BANGLORE RJDHNI"},
{"train_number":"13241","train_name":"BANKA RJPB EXP"},
{"train_number":"15693","train_name":""},
{"train_number":"15694","train_name":""},
{"train_number":"14555","train_name":"BAREILLY DLI EX"},
{"train_number":"14556","train_name":"BAREILLY EXP"},
{"train_number":"14313","train_name":"BAREILLY EXP"},
{"train_number":"14322","train_name":"BAREILLY EXPRES"},
{"train_number":"28624","train_name":"BARKA RJPB EXP"},
{"train_number":"14888","train_name":"BARMER  KLK EXP"},
{"train_number":"14805","train_name":"BARMER AC EXP"},
{"train_number":"17308","train_name":"BASAVA EXPRESS"},
{"train_number":"17307","train_name":"BASAVA EXPRESS"},
{"train_number":"51029","train_name":"CSTM BJP PASSENGER"},
{"train_number":"18404","train_name":"BBN CKP INT EXP"},
{"train_number":"12022","train_name":"BBN JANSHATABDI"},
{"train_number":"12021","train_name":"BBN JANSHATABDI"},
{"train_number":"18415","train_name":"BBN PURI EXP"},
{"train_number":"12831","train_name":"BBS  GARIB RATH"},
{"train_number":"12892","train_name":"BBS BPO EXPRESS"},
{"train_number":"18437","train_name":"BBS BWIP LINK E"},
{"train_number":"12830","train_name":"BBS CHENNAI EXP"},
{"train_number":"01020","train_name":""},
{"train_number":"12282","train_name":"BBS DURONTO EXP"},
{"train_number":"12281","train_name":"BBS DURONTO EXP"},
{"train_number":"12894","train_name":"BBS EXPRESS"},
{"train_number":"12073","train_name":"BBS JAN SHATABD"},
{"train_number":"12074","train_name":"BBS JAN SHATABD"},
{"train_number":"12880","train_name":"BBS LTT SF EXP"},
{"train_number":"02815","train_name":""},
{"train_number":"02281","train_name":""},
{"train_number":"22805","train_name":"BBS ANVT SUP EX"},
{"train_number":"12898","train_name":"BBS PDY EXPRESS"},
{"train_number":"08449","train_name":""},
{"train_number":"22882","train_name":"BBS PUNE EXP"},
{"train_number":"12582","train_name":"NDLS MUV SF EXP"},
{"train_number":"02882","train_name":""},
{"train_number":"22811","train_name":"BBS RAJDHANI EX"},
{"train_number":"22823","train_name":"BBS RAJDHANI EX"},
{"train_number":"18496","train_name":"BBS RMM EXPRESS"},
{"train_number":"18106","train_name":"BBS ROU INT EXP"},
{"train_number":"08464","train_name":""},
{"train_number":"22871","train_name":"BBS TPTY EXPRES"},
{"train_number":"22879","train_name":"BBS TPTY SUP EX"},
{"train_number":"02845","train_name":""},
{"train_number":"12845","train_name":"BBS BNC SUP EXP"},
{"train_number":"09017","train_name":""},
